### ISSUE TITLE
C++ compatible headers

### ISSUE THREAD

**Issue by theultramage** [HerculesWS/Hercules#1132]
I've been told that eventually the code will use C-specific constructs, but that doesn't mean the headers can't be C++ compatible. That would allow older visual studio compilers to build custom modules/plugins in C++ mode, the main benefit being C'99 style variable declaration placement. It seems that just a few tweaks are needed:

itemdb.h(625): error C2899: typename cannot be used outside a template declaration
```
struct itemdb_interface {
	const char* (*typename) (int type);
```
storage.h(76): error C2059: syntax error : 'delete'
```
struct guild_storage_interface {
	int (*delete) (int guild_id);
```
HPMSymbols.inc.h(263): error C2440: '=' : cannot convert from 'void \*' to atcommand_interface \*'. Conversion from 'void*' to pointer to non-'void' requires an explicit cast
```
HPExport void *(*import_symbol) (char *name, unsigned int pID);
#define HPM_SYMBOL(n, s) ((s) = import_symbol((n),HPMi->pid))

if ((server_type&(SERVER_TYPE_MAP)) && !HPM_SYMBOL("atcommand", atcommand)) return "atcommand";
```

**Comment by hemagx** [comment]
to mention support for old compilers is dropped from hercules and we will drop more possible old compilers by time, the cast from void to anything without an explicit case will be used often much soon.

**Comment by MishimaHaruna** [comment]
I'm strongly against adding any c++ compatibility, if it decreases the quality or readability of code.

This includes:

- Use of identifiers that are reserved in C++.

For example, there are several `class_` that are awfully ugly, and I'd like to change them to `class`, without having to worry about the code being able to compile as  C++, Objective-C, LOLCODE, brainfuck, Befunge or whatever other language one might come up with, whether it remotely resembles the C syntax or not. If the code is written in C99, it must observe the C99 rules and nothing else.

- Explicit casts.

We're getting rid of all of them, since they nastily hide other issues when code is refactored. Supporting C++ would force us to keep those.

- Flexible arrays.

For whatever reason, the C++ designers decided not to support those, while we want to (and we do) use them in our headers.

**Comment by theultramage** [comment]
Reserved identifiers - okay I guess, I looked it up and it can be worked around using trickery like ```#define typename typename_```. I'm okay with that.

Explicit casts - well, voidp to typep is already as unsafe as it gets. What sort of nasty issues do they hide? Btw, all the casts are in .c files, this is the only conflict in a header file. Would it be possible to move that nasty HPM_shared_symbols() function into a .c file?

Flexible arrays - not a problem, they normally don't appear in header files, unless you write inline code. I hope.

**Comment by MishimaHaruna** [comment]
Explicit casts: I was mostly referring to places that aren't in headers, indeed, but rather, in source files.  (I was thinking of cd5a209c126c1daca0df1f82587e1d53af35ccdd).
The places where I feel that explicit casts are very awkward are mostly when you're refactoring code to add a 'const' qualifier to a variable/argument. If the function body (or a contained macro) has explicit casts, you risk not noticing that you're dropping the qualifier.

About HPM_shared_symbols, the reason why it lives in a .inc.h is that you have to include it in any plugins you compile, for them work correctly. It's a function that, depending on whether it's compiled in the core or in a plugin, exports or imports shared symbols.

About flexible arrays: we use them in some structs (see `struct packet_quest_list_info`), especially in clif code (right now they're in packets_struct.h, which will soon become a private header of the clif interface (clif.p.h or whatever), which will be usable from both clif.c and any plugins that need it (we're going to use a PIMPL pattern for our interfaces). It's true that it's limited to certain .h files, but you will be unable to use those as C++.

Another thing I forgot mentioning in point 1 is that C++ automatically clutters the identifier namespace when you define an enum or a struct (`struct foo;` results in an automatic and inevitable `typedef struct foo foo;`, preventing us to use 'foo' as variable name, while we might want to (and probably do use it).

Something else to consider, when compiling as C++ is that I'm not sure whether plugins would work at all, since the C++ compiler does its nasty things (name mangling, etc).

**Comment by theultramage** [comment]
I concur that if targeting C++ is not the goal, then the following changes are not as desirable. I'll just leave them here for anyone who happens to want to build their plugin this way. Note that if you ever want to go C'99 to clean up the ugly variable placement, and still support the MSVC compiler, you'll either have to switch it to compile as C++, or drop compatibility with all VS versions up to at least 2013.

First, we need these defines at the beginning to make various basic headers happy:
```C
#ifdef __cplusplus
#define __bool_true_false_are_defined
#define __STDC_CONSTANT_MACROS
#define __STDC_FORMAT_MACROS
#define _WSPIAPI_H_ // lazy workaround for missing 'extern "C++"' in winsdk
#endif
```
Next, we add defines to rename things in headers that use C++ reserved keywords. This unfortunately messes up standard headers which do use these keywords in a C++ context. To work around this, we need to reorder includes to make sure that the standard headers and (almost) all the common/ headers go first. The header mmo.h might need to be moved in the future.
```diff
+#include <stdio.h>
+#include <stdlib.h>
+#include <string.h>
 
+#ifdef __cplusplus
+extern "C" {
+#endif
 #include "common/hercules.h" /* Should always be the first Hercules file included! (if you don't make it first, you won't be able to use interfaces) */
 #include "common/memmgr.h"
 #include "common/mmo.h"
 #include "common/socket.h"
 #include "common/strlib.h"
+#define typename typename_
+#define delete delete_
+#define class class_
 #include "map/clif.h"
 #include "map/pc.h"
 #include "map/script.h"
 
 #include "common/HPMDataCheck.h" /* should always be the last Hercules file included! (if you don't make it last, it'll intentionally break compile time) */
+#ifdef __cplusplus
+} // extern "C"
+#endif

-#include <stdio.h>
-#include <stdlib.h>
-#include <string.h>
```
Next, we need to address that HPM interface thing. Fortunately, it can be done with just a small tweak:
```diff
src/common/HPMi.h
-HPExport void *(*import_symbol) (char *name, unsigned int pID);
+HPExport void *(*import_symbol) (char *name, void **out_psymbol, unsigned int pID);
-#define HPM_SYMBOL(n, s) ((s) = import_symbol((n),HPMi->pid))
+#define HPM_SYMBOL(n, s) (import_symbol((n),(void**)&(s),HPMi->pid))
```
```diff
src/common/HPM.c
-void *hplugin_import_symbol(char *name, unsigned int pID)
+void *hplugin_import_symbol(char *name, void **out_psymbol, unsigned int pID)
 {
 	int i;
 	ARR_FIND(0, VECTOR_LENGTH(HPM->symbols), i, strcmp(VECTOR_INDEX(HPM->symbols, i)->name, name) == 0);
 
 	if (i != VECTOR_LENGTH(HPM->symbols))
-		return VECTOR_INDEX(HPM->symbols, i)->ptr;
+		return *out_psymbol= VECTOR_INDEX(HPM->symbols, i)->ptr;
 
 	ShowError("HPM:get_symbol:%s: '"CL_WHITE"%s"CL_RESET"' not found!\n",HPM->pid2name(pID),name);
-	return NULL;
+	return *out_psymbol= NULL;
 }
```
Almost done. Next we need to ensure that all symbols exported from our plugin have undecorated C names. At the moment of writing, there is an unresolved issue regarding how hercules exports symobls.

Finally, fix up all the remaining trivial void* to type* errors, then right-click on the .c file in msvc's solution explorer, go Properties -> C/C+ -> Advanced -> Compile As, and change it to "Compile as C++ Code". Or just rename the file to .cpp.
