### ISSUE TITLE
Divorce NPC not working.

### ISSUE THREAD

**Issue by kubixservice** [HerculesWS/Hercules#1176]
Divorce (npc/other/divorce.txt) not working because the character is dead.

change
```
percentheal -100,-100;
divorce;
```
to
```
divorce;
percentheal -100,-100;
```

Video: https://youtu.be/iJNzJork0GU

using last GIT Hercules.

**Comment by hemagx** [comment]
i don't remember it kills you on officail but just huge HP lose, can
any of scripts holders confirm ?

@Dastgir @Jedzkie

2016-03-01 13:43 جرينتش+02:00, kubixservice <notifications@github.com>:

**Comment by Emistry** [comment]
anyway, in case you want to kill a players, I think it's better to use this instead.
```unitkill getcharid(3);```

**Comment by Jedzkie** [comment]
@hemagx 

I didn't or never tried the marriage and divorce system on Official Servers..

But base on my Aegis script, this is how it looks like.

`
if v[VAR_MONEY] > 2499999
	ShowEffect "Deviruchi#Divorce" EF_MAGICROD
	ShowEffect "" EF_DEVIL
	dropgold 2500000
	hpdrain 50
	hpdrain 50
	spdrain 100
	divorce
	dialog "[Deviruchi]"
	dialog "I will cancel the oath of marriage before you have any second thoughts!!"
	dialog "Kekeke. You're alone! You're free now!"
	dialog "Throw away all those bad feelings of yours!"
	dialog "You should thank Deviruchi.....!"
	close
`

Not sure about this `hpdrain` and `spdrain` script of aegis, I don't know what it's behavior.

**Comment by kubixservice** [comment]
Up?

**Comment by Emistry** [comment]
about the ring removal issue, I think its no longer exist in latest Herc.

**Comment by Ridley8819** [comment]
I just tested it, it does

**Comment by hemagx** [comment]
I would prefer to get a new script function that cause drain without kill the player, and use it in such cases.

**Comment by MishimaHaruna** [comment]
How can the HP go to zero without dying? If you have 1 HP and receive 1 damage, are you supposed to be still alive? Does death occur on 0 HP or on less-than-0 HP on official servers?

If death occurs when reaching 0 HP, I'm against allowing a character with 0 HP to be alive, and I'd change the script to leave the character with 1 HP/SP instead.

**Comment by Emistry** [comment]
the last time i test the npc script, it work just fine ... capable to divorce without fail.
doesnt have issue with the `percentheal` killing the char and terminated the script or caused the player stuck in the middle.

**Comment by Ridley8819** [comment]
i tested it right before my post, i was killed and the rest of the script wasn't executed. I too think it would be best to simply reduce hp and sp to 1, even if it is 0 on aegis. this would cause again exceptions for trivial things which could cause trouble elsewhere again.

**Comment by Ridley8819** [comment]
This also affects npc\cities\umbala.txt script
@AtlantisRO provided me an aegis replay, I will do a gif later. 
I'd also like to mention#840 #889 and 8b01c8f

**Comment by Ridley8819** [comment]
@hemagx @MishimaHaruna 
Here the said gifs. HP set to 0 during bungee quest
https://i.gyazo.com/757b61263bbeb6fb278acfb3457ee70e.gif

afterwards the hp recovery didn't apply. HP stay on 0 even after switching maps or using kafra teleport. You need to die in order to gain 1 HP back
https://i.gyazo.com/b5f11f11e9985edf03fefceb24b62294.gif

PS: No money for a divorce :P

**Comment by Ragno1** [comment]
I have something to share. Percentheal -100,-100 stops script execution if there is a message (mes) active, but, if you use close2; it doesn't stop the execution.

I use this script for testing:

`prontera,50,50,0	script	test	PORING,{
	mes "this is a test";
	close2;
	percentheal -100,0;
	divorce;
	mes "done";
	close;
}`

Just after clic on close, it does kill the character and let him divorce. Also puts a new message with done and puts a new close button. So, it allows to stay the script execution, instead of stop it.

**Comment by Ragn0** [comment]
About player with 0 hp and being alive it seems to be a bug on Aegis (since it is possible on iRO, like seen on gifs), but looks like a bug, not intended behavior. However, 0 hp, is not totally blocked on Hercules .

I remember one case where you can make a player to walk while beeing with 0 current hp.
Just force them to sit() while beeing dead and they will sit with 0 hp.
Other players will see it on sit status, but player will be dead.
To make him walk just use @refresh or other methods to summon, like wedding skills.

Of course, there is no natural way a player can reach this weird behavior, only happens with custom scripts and can be blocked by checking current player's hp before force them to sit.

**Comment by MishimaHaruna** [comment]
Related commit: f0fc96a130ac67d894e44e922504504587b53bb3
It indeed allows scripts to continue execution if there's no open message dialog. The linked topic (note: dead link, but you have to replace `hercules.ws` with `herc.ws` and it'll be a valid link) also gives a hint as to why we have script execution normally terminate on death:

> however, isn't it meant to be a exploit-countermeasure? so that you can't maintain npc dialogs and use other functionality while dead

**Comment by Ragn0** [comment]
Even when it is noticed the concern about taking care with exploits, I don't think make player cancel dialogue when dead may be a good choise, since it makes you capable to talk again with npc in situations where you normally would not, just like on instances.

By example, there is Endless Tower where after defeat Nagh Sieger you can talk with `Lost Soul#102` npc and have a chance to change some swords for another one and then must be warped to Alberta. If player can cancel the dialogue would be capable to talk again to the npc and do again the change.

I know that may not be a big deal, but it's only for example. I don't want to tell which others npc can be exploited by this behavior.

**Comment by eyes-like-a-hawk** [comment]
bump
