### ISSUE TITLE
sql-files mobskilldb

### ISSUE THREAD

**Issue by reunite-ro** [HerculesWS/Hercules#1180]
`REPLACE INTO `mob_skill_db` VALUES (2220,'Messenger of Devil@NPC_EMOTION','idle',197,1,2000,0,,'yes','self','always',NULL,29,NULL,NULL,NULL,NULL,NULL,NULL);`

theres problem with this line

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''yes','self','always',NULL,29,NULL,NULL,NULL,NULL,NULL,NULL)' at line 1

**Comment by reunite-ro** [comment]
hello. i found this still problem~

**Comment by Kolkka** [comment]
**Should this be fixed in the source file (db/re/mob_skill_db.txt) ?**

Line 7017:
`2220,Messenger of Devil@NPC_EMOTION,idle,197,1,2000,0,,yes,self,always,,29,,,,,,`

Should be:
`2220,Messenger of Devil@NPC_EMOTION,idle,197,1,2000,0,5000,yes,self,always,,29,,,,,,`

**Or should it be fixed in sql-files/mob_skill_db_re.sql ?**

Line 6947:
`REPLACE INTO `mob_skill_db` VALUES (2220,'Messenger of Devil@NPC_EMOTION','idle',197,1,2000,0,,'yes','self','always',NULL,29,NULL,NULL,NULL,NULL,NULL,NULL);`

Should be:
`REPLACE INTO `mob_skill_db` VALUES (2220,'Messenger of Devil@NPC_EMOTION','idle',197,1,2000,0,5000,'yes','self','always',NULL,29,NULL,NULL,NULL,NULL,NULL,NULL);`

**Or should it be fixed in both files?**

**Comment by MishimaHaruna** [comment]
I regenerated the sql script (last time I had probably used a faulty conversion script). The .txt file works even if a field is empty, while in the sql script, a zero is necessary.
