### ISSUE TITLE
autobonus doesn't work on item combo

### ISSUE THREAD

**Issue by memoryss1** [HerculesWS/Hercules#1190]

**Comment by bangzeed** [comment]
about this 

http://herc.ws/board/topic/12095-item-combo-and-getrefine-bug/

**Comment by memoryss1** [comment]
getrefine problem you can simply change it to getequiprefinerycnt

**Comment by memoryss1** [comment]
@MishimaHaruna This is not a question@@

**Comment by Playtester** [comment]
Yeah this is actually a bug. Autobonus assigning the equipment position to the bonus so it can remember when to remove it. It doesn't work with the new combo db format. You would need to create one identifier for any of the 800+ possible equip position combinations and then assign the autobonus to that to implement it properly, but so much work. X_X

I did a temporary solution on rAthena, not sure if Herc has that...

https://github.com/rathena/rathena/commit/b6b6b1366a6d30f38bcc895f9215ddee66c5976a That one.

**Comment by iRagno** [comment]
The issue persist on actual repo. Tested on 9fba7e8c5966bb0aa5ce1c31ebe5cec96180e1d5

How to reproduce:

Put this script into any combo:

`autobonus "{ bonus bStr, 10; }",1000,5000,BF_WEAPON,"{ specialeffect2 EF_POTION_BERSERK; }";`

That script brings 100% chance of set Str+10 for 5 seconds with specialeffect EF_POTION_BERSERK. However, when contained into item_combo_db this script doesnt work. Then, put the same script on any item on item_db.conf and autobonus will triger.

There are several items damaged because of this. I have fixed it locally by bringing those autobonuses into item_db.conf, until item_combdo_db.txt gets fixed.

**Comment by iRagno** [comment]
@Ridley8819, you forgot to reopen this.

**Comment by MrKeiKun** [comment]
> 
> 
> The issue persist on actual repo. Tested on [9fba7e8](https://github.com/HerculesWS/Hercules/commit/9fba7e8c5966bb0aa5ce1c31ebe5cec96180e1d5)
> 
> How to reproduce:
> 
> Put this script into any combo:
> 
> `autobonus "{ bonus bStr, 10; }",1000,5000,BF_WEAPON,"{ specialeffect2 EF_POTION_BERSERK; }";`
> 
> That script brings 100% chance of set Str+10 for 5 seconds with specialeffect EF_POTION_BERSERK. However, when contained into item_combo_db this script doesnt work. Then, put the same script on any item on item_db.conf and autobonus will triger.
> 
> There are several items damaged because of this. I have fixed it locally by bringing those autobonuses into item_db.conf, until item_combdo_db.txt gets fixed.
> 
> @HerculesWS/developers


Requesting to re-open this since the bug exist right now. with same idea of autobonus not working under item_combo

**Comment by Nurkz** [comment]
Duplicate of #2764
