### ISSUE TITLE
Land Protector Border #2

### ISSUE THREAD

**Issue by kubixservice** [HerculesWS/Hercules#1203]
Old topic: http://herc.ws/board/tracker/issue-5237-land-protector-border/

LP didn't work again.
Using last GIT Hercules:

Screens:
http://i66.tinypic.com/2ymzywg.jpg
http://i66.tinypic.com/2dhu453.jpg

**Comment by WillTheDoggy** [comment]
Please read this thread.

http://herc.ws/board/tracker/issue-8693-land-protector-meteor-storm-bug/

LP does NOT protect against **SPLASH** damage, which Storm gust and Meteor Storm does. It is working as intended.

Yes this affects your sterotypical GvG environment. Just reverse that particular commit.

**Comment by Playtester** [comment]
Actually the topic linked in the first post talks about exactly that. Working as intended for both pre-renewal and renewal.

I was thinking about a config too, but the problem is that it's an inheritely different structural approach to the implementation of unit skills. And affects many things. Better let server owners customize it as they prefer.

Also, I see that most players actually like the splashing into LP. It makes WoE much more interesting and each skill unique in how far it can hit into LP. What many don't like is that LP removes ground effects so even if you remove LP it won't start dealing damage immediately, I know many server owners revert that one (like, LP doesn't remove units at all anymore).

Also there is a problem with Meteor Storm itself. On official servers it places all units directly at castend, so if you cast LP, it will remove all of them immediately, so even if LP is removed later on, no meteor will start falling until you cast it again. But again, no server owner wants to add that, so it's hard to find the motivation to put effort into implemented that. If you think MS is too powerful, however, this would be the official fix for that.

**Comment by kubixservice** [comment]
Hello!
Can you tell me how to properly revert commit which introduces changes to LP?

**Comment by Playtester** [comment]
I think if you just want to prevent the splash then you only need to change two lines.

These are the changes you'd like to revert:
```
-	if( skill->get_type(sg->skill_id) == BF_MAGIC && map->getcell(bl->m, bl->x, bl->y, CELL_CHKLANDPROTECTOR) && sg->skill_id != SA_LANDPROTECTOR )
+	if( skill->get_type(sg->skill_id) == BF_MAGIC && map->getcell(src->bl.m, src->bl.x, src->bl.y, CELL_CHKLANDPROTECTOR) && sg->skill_id != SA_LANDPROTECTOR )
```

```
-	if( !(skill->get_inf2(group->skill_id)&(INF2_SONG_DANCE|INF2_TRAP|INF2_NOLP)) && map->getcell(bl->m, bl->x, bl->y, CELL_CHKLANDPROTECTOR) )
+	if( !(skill->get_inf2(group->skill_id)&(INF2_SONG_DANCE|INF2_TRAP|INF2_NOLP)) && map->getcell(su->bl.m, su->bl.x, su->bl.y, CELL_CHKLANDPROTECTOR) )
```

(the line with + is the current one and the one with - is the one you want)

**Comment by Smit1237** [comment]
Hmmm, working on same issue, last revision, got erro while compiling
http://pastebin.com/E8sMa1kG
Any suggestions how to fix that?

**Comment by Playtester** [comment]
Ah Herc updated the function structure since then.

You need to add "bl" as second argument.

```if( skill->get_type(sg->skill_id) == BF_MAGIC && map->getcell(bl->m, bl, bl->x, bl->y, CELL_CHKLANDPROTECTOR) && sg->skill_id != SA_LANDPROTECTOR )```

```if( !(skill->get_inf2(group->skill_id)&(INF2_SONG_DANCE|INF2_TRAP|INF2_NOLP)) && map->getcell(bl->m, bl, bl->x, bl->y, CELL_CHKLANDPROTECTOR) )```

**Comment by Smit1237** [comment]
@Playtester Thanks a lot. Now compiled without issue. Still need to test, but anyway big thanks :)

**Comment by Smit1237** [comment]
@Playtester Tested, working  exactly as i want, i think issue resolved and can be closed :)
