### ISSUE TITLE
Attack Speed Bug (2)

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1204]
Bug: When a Claw type weapon is worn by a Priest it decreases its attack speed down to 2 (with 3 agi).
~ Tested on latest and 7 months old revision
~ Pre-Renewal
![ss1](https://cloud.githubusercontent.com/assets/4656578/13898410/2d4ac5a0-ee0b-11e5-93d7-eec27f568b87.jpg)

**Comment by Emistry** [comment]
I guess the aspd calculation for character that equipped the weapon class that doesn't belong to them isn't supported. 

Example : An acolyte will never equip with an Katar. So this case will probably has no chance to occur in official server

**Comment by hemagx** [comment]
not bug ? you're not even meant to wear it. as simple as it seem.

2016-03-19 14:13 جرينتش+02:00, Emistry Haoyan <notifications@github.com>:

**Comment by MishimaHaruna** [comment]
This has always been the case as far as I'm aware... I've always thought it was intended even if very stupid (i.e. I always wanted to play a priest using a knuckle weapon but never could because of this ridiculous aspd reduction).

@emistry, @hemagx: priests can wear knuckles so that's not the problem


In the stat simulator provided by irowiki, the aspd value is much higher than that (but maybe something changed in renewal?)

This pre-re stat simulator has very low values, but I have no idea whether it uses our formulas or the official ones http://calcx.wushuang.ws/?cajababababababababanaaktaaaaaaaaae5aaaaaaaaacsaad5aaeueFaafbaafhaafqaafqaaaaaaadaaaaaabaaacuaaaaHaaaa

**Comment by malufett** [comment]
if you will check the aspd table for priest it is set to 2000(lowest default).
ok let's compute...
amotion = 2000
amotion -= 2000 * (4 * 3 + 1) / 1000
amotion -= 2000 * (13) / 1000
amotion -= 26000 / 1000
amotion  = 2000 - 1974
amotion = 26 or (2000-26/10 = 1.9 round off to 2 aspd )
..if someone knows the official value then set it in the job_db.conf

![image](https://cloud.githubusercontent.com/assets/3251821/13899978/2781206c-ee36-11e5-92c6-c7eca30821f6.png)

**Comment by AtlantisRO** [comment]
We do a test in iRO Classic.Loki with a Priest (base stats Agi 57 and Dex 60) equipping a Waghnak. Here is the results:

Note: The "total" value is the raw aspd calculated according to the formula, assuming a value of 2000 for weapon delay.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Agi 57 | Dex 60 | 57 window aspd (57.6 total aspd)
Agi 60 | Dex 60 | 60 window aspd (60.0 total aspd)
Agi 61 | Dex 60 | 60 window aspd (60.8 total aspd)
Agi 62 | Dex 60 | 61 window aspd (61.6 total aspd)
Agi 63 | Dex 60 | 62 window aspd (62.4 total aspd)
Agi 64 | Dex 60 | 63 window aspd (63.2 total aspd)
Agi 65 | Dex 60 | 64 window aspd (64.0 total aspd)
Agi 66 | Dex 60 | 64 window aspd (64.8 total aspd)
Agi 67 | Dex 60 | 65 window aspd (65.6 total aspd)
Agi 68 | Dex 60 | 66 window aspd (66.4 total aspd)
Agi 69 | Dex 60 | 67 window aspd (67.2 total aspd)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Agi 57 | Dex 60 | 57 window aspd (57.6 total aspd)
Agi 57 | Dex 61 | 57 window aspd (57.8 total aspd)
Agi 57 | Dex 62 | 58 window aspd (58.0 total aspd)
Agi 57 | Dex 63 | 58 window aspd (58.2 total aspd)
Agi 57 | Dex 64 | 58 window aspd (58.4 total aspd)
Agi 57 | Dex 65 | 58 window aspd (58.6 total aspd)
Agi 57 | Dex 66 | 58 window aspd (58.8 total aspd)
Agi 57 | Dex 68 | 59 window aspd (59.0 total aspd)
Agi 57 | Dex 69 | 59 window aspd (59.2 total aspd)
Agi 57 | Dex 70 | 59 window aspd (59.4 total aspd)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Weapon Delay for Knuckles in iRO Classic.Loki is confirmed as 2000 making this bug also in officials (at least in iRO Classic).

**Comment by Playtester** [comment]
Yeah, it's always been like that ever since monks got added. Priest could equip knuckles, but lost all their ASPD because it's not defined for priests.

I think they fixed it in renewal at some point.

**Comment by iRagno** [comment]
This is official behaviour. Officialy Priest never got Weapon Delay for Knuckles and that is the motive to drop all the aspd when use it.

I still have the Priest commented by @AtlantisRO on 19 Mar 2016 and just did another test today with similar results on iRO Classic, that has pre-renewal mechanics.

Since it's official behaviour, why not just bring a commented value on db\pre-re\job_db.conf adding a value of 500 for Knuckles on Priest? In that way, Admins could choose to fix it by removing comment to that line or leave it commented as official behaviour, allowing to complete this issue.

**Comment by Mysteries** [comment]
Either way, this can be closed since it is official behaviour. I also don't mind having that option set for Priest either as @iRagno mentioned. Shouldn't hurt.

**Comment by iRagno** [comment]
I think this can be closed, @Mysteries.
