### ISSUE TITLE
Improvised Song not working

### ISSUE THREAD

**Issue by Shyne** [HerculesWS/Hercules#1211]
Improvised Song not release any magic skill.
I tried use @addperm skill_unconditional to spam but nothing.

**Comment by Kenpachi2k13** [comment]
This happens because `sd->state.abra_flag` is set to 0 in `skill_check_condition_castbegin()`.
For Hocus-Pocus skills, this is correct, because they require catalyst items.
Since skills, casted by Improvised Song, do **NOT** require catalyst items, `sd->state.abra_flag` should only be set to 0 in `skill_check_condition_castbegin()`, if it's value is 1 (Hocus-Pocus).
If `sd->state.abra_flag` is 2 (Improvised Song), it should be kept for usage in `skill_check_condition_castend()`.
