### ISSUE TITLE
NPC allow changing of equipments while interacting

### ISSUE THREAD

**Issue by Emistry** [HerculesWS/Hercules#1221]
# issue Preview

When first talk to the NPC...
![GitHub Logo](http://i.imgur.com/1kvuwGO.png)

After the **Shop Window** opened.
![GitHub Logo](http://i.imgur.com/dMwNqN3.gif)
# How to Reproduce the Issue

```
// Enable all NPC to allow changing of equipments while interacting? (Note 1)
// Script commands 'enable_items/disable_items' will not be override. (see doc/script_commands.txt)
// 1 : yes(official)
// 0 : no
item_enabled_npc: 0
```
1. Change the setting in **conf/battle/item.conf**.
2. Create several items with same ID. _(Example: Katana [3])_
3. Place the items in the Hotkey bars.
4. Load the NPC script. https://pastebin.com/kZmUQx8D
5. Talk to the NPC and spam click the Hotkey to switch equipments.
# Result
- At first, your character unable to switch equipment no matter how you spam click the hotkey.
- After **Enter** pressed, the **Shop window** is opened.
  - first few click, might still success to block equipment switching.
  - **afterward, it will success to switch the equipment**.
- although success to switch equipment at the end, the selling progress might still failed, but the behaviour isn't correct. Players are suppose remain unable to exchange equipment.

**Comment by josetaas** [comment]
Yeah, I remember this being abused before on servers with a costume preview NPC. It seems that ```end``` will lead to a ```free_state``` call which sets ```npc_id``` to 0. Hence, after a short moment, you can start equipping items again. The only way I can think of at the moment is to just flag shops with a script attached to them as an NPC interaction, as well.

**Comment by MishimaHaruna** [comment]
Other than incorrect behavior (my opinion is that it's stupid to restrict actions without a reason, but oh well, so much for emulating Aegis limitations and their lack of user input validation), there really shouldn't be anything abusable here.

This kind of script seems pretty much an abuse of the scripting system. After an 'end', the script terminates, and none of its side effects is supposed to have effect anymore (correct behavior would be that the effect of disable_items ends immediately). Expecting it to still work sounds wrong (and if it does, I hope it wasn't intentional)

**Comment by Emistry** [comment]
yes currently it doesn't seem like bringing any negative effect to server and it's also a trick/hack to use npc like this. :D

but isn't opening a shop would also consider as "interaction with NPC" ?

**Comment by MishimaHaruna** [comment]
But interaction with the script ends where the 'end' or 'close' command is... So anything past it is a new instance of the script execution...

**Comment by josetaas** [comment]
Well, it does seem that it should be the way it is. It only looks weird because the script called ```end``` and left the NPC dialogue window still open, even though the state has already been cleaned. My memory is foggy, but I do remember now that a certain preview headgear script was exploitable during the NPC dialogue (not the shop display), hence remedied by ```item_enabled_npc```.

**Comment by Kenpachi2k13** [comment]
As stated by @MishimaHaruna this works as intended and isn't a bug.
`close();`
