### ISSUE TITLE
Unable to get item

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1241]
Picking up an item that is across you while there is something (player/NPC/mob) blocking the cell between you and the item will result to making you back and forth trying to get the item.
This bug only happens when the item you're trying to pick up was on your left side of the screen. (Just like in the video.)
Hercules:
https://youtu.be/QmmX846hu30

Aegis Video:
https://youtu.be/vbMF2s8xUEo

**Comment by malufett** [comment]
hahaha..poor monk..

**Comment by Lemongrass3110** [comment]
Maybe you can get some useful things from here rathena/rathena#198
It's exactly the issue you are describing.

**Comment by Playtester** [comment]
I want to note that the actual movement looping is the official behavior. We removed it on rAthena though... custom change, but everyone except me wanted it.

Whether you pick up the item or not simply depends on your latency. If latency is high enough, client will send a "TakeItem" request, because it thinks you've reached the cell by now. rAthena/Herc however are a lot more reactive than Aegis and already tell the client to move back because the cell is occupied before the client thinks it has reached the cell.

You'd need to implement artificial lag to solve this~

If I have very good connection to official server, it will also loop instead of picking up the item. Or rather, it loops until there is a lag spike, then pick up the item.

**Comment by Playtester** [comment]
I want to note that the actual movement looping is the official behavior. We removed it on rAthena though... custom change, but everyone except me wanted it.

Whether you pick up the item or not simply depends on your latency. If latency is high enough, client will send a "TakeItem" request, because it thinks you've reached the cell by now. rAthena/Herc however are a lot more reactive than Aegis and already tell the client to move back because the cell is occupied before the client thinks it has reached the cell.

You'd need to implement artificial lag to solve this~

If I have very good connection to official server, it will also loop instead of picking up the item. Or rather, it loops until there is a lag spike, then pick up the item.

**Comment by Playtester** [comment]
Official is official.

Longer explanation: Official is the only common ground you can find in an open source project. If you allow even just slight differences from official you will start getting debates over whether something should be done or should not be done and in the end there will be conflicts, people reverting other people's code or people leaving out of frustration. Not to mention all the time that's wasted with these debates which could have been used to fix 2-3 more bugs.

Also no matter how silly something seems, often it has large influences on different tactics that a single person usually can't oversee. You might think BB gutter line is a stupid bug, but it's also the only reason to get Brandish Spear instead, despite much lower damage and only half the status  change chance. You might think how monsters behave officially when trapped in ice wall is super dumb, but then you see all the cool jRO videos with funny tactics that actually make Agi Wizards viable. There's no clear line where you can start saying "It's too bugged, it should not be done."

Not to mention all the follow-up issues that appear when your core isn't official. You can't implement skills properly because of the differences in the core, so you create workarounds. Later you find a bug with a skill, but can't fix it because the workaround is in the way. With an official core you could often fix all the skills with just a single line change. Really, 90% of the pre-renewal fixes I still need to do are due to all the skills simply just implemented by what makes sense rather than by how it officially works and that gives me a lot of extra work.

**Comment by MishimaHaruna** [comment]
Once again, emulating obvious official bugs isn't a goal of this project. Fixing them is part of our goal. Providing a way for the users to enable the bugs (or disable them) via configuration gains bonus points.
