### ISSUE TITLE
Compile Error (Centos 6)

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1262]
./configure && make clean && make sql && make plugins

`        CC      HPMHooking.c (MAP)
{standard input}: Assembler messages:
{standard input}:68227: Warning: end of file not at end of a line; newline inser                                 ted
{standard input}:69396: Error: suffix or operands invalid for `movq'
{standard input}:69396: Error: open CFI at the end of file; missing .cfi_endproc                                  directive
gcc: Internal error: Killed (program cc1)
Please submit a full bug report.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[1]: *** [../../plugins/HPMHooking_map.so] Error 1
make[1]: Leaving directory `/root/xxx/src/plugins'
make: *** [plugins] Error 2
`

**Comment by dastgir** [comment]
CentOS 6 uses old GCC which consumes GB's to compile HpmHook.
Mostly, you went out of memeory

**Comment by tlacson7** [comment]
You where correct dastgir, it run out of memory, i close running apps and compiled successfully.

**Comment by MishimaHaruna** [comment]
To compile on CentOS 6 (if you can't upgrade to CentOS 7), we recommend to at least upgrade the developer tools to a more recent version, since the one bundled with the distribution is severely outdated (and we can't guarantee that it'll continue working).
The devtoolset version 2 contains gcc-4.8, which is recent enough to correctly compile Hercules.  http://people.centos.org/tru/devtools-2/readme
