### ISSUE TITLE
Party Chat cuts off last letter

### ISSUE THREAD

**Issue by Nihadm89** [HerculesWS/Hercules#1270]
I believe it has been caused by this update though I am not 100% sure.
https://github.com/HerculesWS/Hercules/commit/2b1dce1e4acf46941657cab6da008c774f52de7c
However, when using party chat the last letter gets cut off.

**Comment by kyeme** [comment]
I can confirm.. @MishimaHaruna

**Comment by MishimaHaruna** [comment]
2b1dce1 is unrelated, 4788c81 doesn't affect party chat (but might cause a similar issue in the battleground chat, now that I look at it).

Since I'm unable to test on a 2015 client, could you check if it works correctly in 3ccc681a4bebd5b91b96c1c7059fdec91f2b5d16 ? Either ways, I'm going to re-review those commits, there might be a few '+1' that slipped under my radar

**Comment by kyeme** [comment]
@MishimaHaruna Still bugged in https://github.com/HerculesWS/Hercules/commit/3ccc681a4bebd5b91b96c1c7059fdec91f2b5d16

**Comment by Smokexyz** [comment]
clif_process_message

**Comment by MishimaHaruna** [comment]
Fixed, thank you very much!
