### ISSUE TITLE
*getskilllist and *skill script commands

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#1306]
When used to store the current skills and their levels and then to allocate the saved values, certain skills are just ignored, here's the list:

GS_BULLSEYE
GS_MADNESSCANCEL
GS_ADJUSTMENT
RK_HUNDREDSPEAR
AB_EPICLESIS
AB_EUCHARISTICA
WS_CARTBOOST
WS_CARTTERMINATION
WA_SWING_DANCE
WA_SYMPHONY_OF_LOVER
WA_MOONLIT_SERENADE
MI_RUSH_WINDMILL
MI_ECHOSONG
MI_HARMONIZE
MO_SPIRITSRECOVERY
MO_BODYRELOCATION

And a script to test this with:

http://herc.ws/board/topic/12384-build-manager-create-your-builds-and-load-them-when-you-want-for-stats-and-skills/

Update: It appears those skills do get allocated after you change a map but not upon relog, relogging before a map change will make the skill gone for good. So this is probably related to clif_addskill or something else.

**Comment by guilherme-gm** [comment]
The problem happens when you learn a skill that has pre-requisites that you currently don't have.
For example GS_BULLSEYE (ID 503) requires GS_TRACKING (ID 512), if you learn the skills in id order, 503 is added before you have 512, so it's removed.
This happens on pc_calc_skilltree, it first removes the skill ID and then checks for requirements, so if you have 503 but doesn't have 512, it'll remove 503.
When you warp to another map, it'll recalculate, this time you have 512, so you can have 503 and it appears again.

I don't know a safe way to fix it though.

**Comment by Kenpachi2k13** [comment]
This is not a bug, since the script simply tries to add the skills in incorrect order.
And well, after almost 3 years without any activity it seems as if this isn't important for anyone.
`close();`
