### ISSUE TITLE
Error upon compile (fresh Hercules)

### ISSUE THREAD

**Issue by eyes-like-a-hawk** [HerculesWS/Hercules#1337]
Hiya,

I downloaded a fresh version of Hercules and have done no configurations to it. When I reach at command.c while compiling I encounter this error.

```
make[1]: Entering directory `/home/user(censored)/Hercules/src/map'
        MKDIR   obj_sql
        CC      atcommand.c
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[1]: *** [obj_sql/atcommand.o] Error 4
make[1]: Leaving directory `/home/user(censored)/Hercules/src/map'
make: *** [map_sql] Error 2
user(censored)@censored:~/Hercules$

```

**Comment by MishimaHaruna** [comment]
It sounds like your compiler ran out of RAM memory while building.

You should consider one or more of the following:

- closing running programs
- installing more RAM
- enabling additional swap space
- upgrading to a newer version of the compiler (since the trend seems that they become less memory hungry with new versions)
- disabling LTO in the build options (unless already disabled, it's off by default)

We currently build Hercules with clang 3.4, gcc 4.6, gcc 5.4 and gcc 6.1 without issues (see travis build logs at https://travis-ci.org/HerculesWS/Hercules for reference)

What's your OS version and available RAM?

**Comment by eyes-like-a-hawk** [comment]
Thank you for the quick reply Haru really appreciate it.

I think you are right on the RAM front, since I am also running XenForo and Mediawiki on this host. I intend to install a second test server on this host.

I upgraded from 512mb -> 1024mb and it is working fine now. it never occurred to me we could run out of ram as it's never happened to me before!

Thanks for your response again. I know it is a simple question, but it means a lot being able to get an answer so quickly.
