### ISSUE TITLE
SkillDB Converter.

### ISSUE THREAD

**Issue by dastgir** [HerculesWS/Hercules#1363]
SkillDB Converter provides the output in colored format.
but Windows Command Prompt doesn't support color.
Output on windows is shown as below:
http://pastebin.com/6wEhMquu (Without any newlines)
Maybe add a option to show colored output(and disabled by default?)

**Comment by MishimaHaruna** [comment]
It could default to off on windows (and to on on other OSes).

Are all the versions of windows affected by the way? (including windows 10? As far as I'm aware, the windows 10 cmd.exe supports the ANSI color escapes and is VT-100 compatible)
Older versions of windows also are probably not affected if the command is executed in cygwin or in the git prompt (the bash-based one that comes with SourceTree and various other git installations, and uses mintty instead of cmd.exe)

By the way, those codes you see aren't just colors, it's also the progress bar

**Comment by EPuncker** [comment]
I guess this can be closed as it has been solved?
