### ISSUE TITLE
Skill Point distribution Bug

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#1382]
I change my job directly into any of Transcendent Classes, after that I accommodate the skill points in the 2nd Tab, I noticed that I can apply the skill points on my 2nd Tab even though the Skill Points for 1st Tab aren't used yet. Please do check this if you have time @MishimaHaruna thank you!

Server Settings: Pre-RE
Client: 2010-06-16aRagexeRE Client
Herc GIT Hash: https://github.com/HerculesWS/Hercules/commit/bc46ac94eba15b4f5159a7fa330c93907dad7d68

**Comment by Emistry** [comment]
https://github.com/HerculesWS/Hercules/blob/master/conf/battle/player.conf#L32-L34

**Comment by Jedzkie** [comment]
@Emistry Yah, i already tried that settings but if I set to no, it will still bypass the 1st Tab skills.

**Comment by Emistry** [comment]
you need to set it to `yes` to enforce skill point spend on their respective job.
```
// When set to yes, forces skill points gained from 1st class to be put into 1st class
```

**Comment by Jedzkie** [comment]
@Emistry by default, its yes.

**Comment by iRagno** [comment]
This issue is very similar to #1603. At changing job server sets two special variables saving the job level player has when changing job, and that is used to calculate skill points needed when using services like neuralizer.

These vars are:

jobchange_level : from first to second job
jobchange_level_3rd : from second to third job

Please check Issue #1603 to read more details about it. I really think that is the problem and then this can be closed.

**Comment by Ridley8819** [comment]
I agree with Ragno, During this year since the issue was opened I tried several times to break reproduce this, but I think Ragno's reasoning makes it pretty clear.
