### ISSUE TITLE
npctalk with empty NPC_NAME

### ISSUE THREAD

**Issue by Asheraf** [HerculesWS/Hercules#1523]
Git Hash: e1453434af18b30119114077dfc52d27ad196cef
using the following script

```
prontera,150,150,0	script	#blalalla	4_M_COOKIE,{
	npctalk(_("Some Random Words"));
	end;
}
```

would result in-game the npctalk command show the npc hidden name:
`#blalalla : Some Random Words`

**Comment by Ridley8819** [comment]
There are other issues with npctalk too. Sometimes it ignores the the first letters' capital and then all are small letters, I can't exactly tell how to reproduce, but if you  have several npctalk lines starting with a capital letter, it will occur. 

On Topic: Totally agree for an option to disable the npc name

**Comment by Emistry** [comment]
or we could follow rAthena approach here.
https://github.com/rathena/rathena/commit/321b1d22e819023f40fe72128bb25d4177d83970
`npctalk` no longer append the npcname unless it's provided in the text.

**Comment by Ridley8819** [comment]
Makes honestly less sense to me, since you want the npc name in 90% when you use it. An additional TRUE statement to disable it sounds more userfriendly to me

**Comment by dastgir** [comment]
I agree with ridley, optional parameter to disable npc name seems quite good, and there wont be any trouble from user side too.

**Comment by Ragn0** [comment]
According to Aegis chinese script for Horror Toy Factory Instance, every single npctalk command used in there have manually writed the npc name with no exception.

Because of that, it seems that official script does only show the text provided between quotation marks and does never show any other thing that is not writed in there, even the npc name.

This has been more evident because the npc #fac1bs has npctalk command and texted talked by npc shows a name, but npc has not any visible name making them show the hidden name instead, as Asheraf explains in this issue.
