### ISSUE TITLE
Peuz's Greaves - Wrong bonus script

### ISSUE THREAD

**Issue by ItsWolfeh** [HerculesWS/Hercules#1533]
When refine is below 7, it gives -1 agility, and when above, it gives +1 and only +1. Item description states no negative agility and that you get more than +1 Agi (it's for every refine above 7.)

Script:
bonus bAgi,-7+min(getequiprefinerycnt(EQI_SHOES),8);
Suggested Fix:
if(getequiprefinerycnt(EQI_SHOES)>7) bonus bAgi,getequiprefinerycnt(EQI_SHOES)-7;

**Comment by Mysteries** [comment]
@iRagno

**Comment by iRagno** [comment]
This is description from kRO:

> MSP + 40.
> 8제련 시 부터 제련도 1당 AGI + 1 증가.

And this is description from jRO:

> MaxSP + 40 
> ――――――――――――― 
> [ペオースグリーブ]の 
> 精錬値が8以上の時、 
> 精錬値が1上がる度に追加で 
> Agi + 1 

From translation on Google and Bing, I can say it increases 1 Agi per every refine over 8 (refine 9: +1 agi, refine 10: +2 agi).

bRO description even say it more clearly:

> SP Máx. +40. 
> AGI +1 por refino acima do +8. 

Actual script comes from iRO description:

> MaxSP + 40.
> Reduces AGI by 7. Refine rate reduces the AGI reduction by 1% for each level up to +8.

Since kRO and jRO are coincident, I would say maybe iRO description has a translation error or custom effect.

Script could be changed to:

`bonus bAgi, (getequiprefinerycnt(EQI_SHOES) > 8 ? getequiprefinerycnt(EQI_SHOES) - 8, 0);`

**Comment by iRagno** [comment]
I just get one Peuz Greaves without refine on iRO, and keeps intact Agi when equipped:

![peuz](http://i65.tinypic.com/3022vyb.jpg)

I can say bug is confirmed.

**Comment by iRagno** [comment]
Since I don't know korean and use translators, I have doubt about required level and search for items with similar description. I found this:

13061 - Black Wing [1] :
> Korean: 6제련 시 부터, 제련도 당 해당 스킬의 공격력 2% 추가 증가 , MATK + 3씩 증가.
> English: 2% ATK and +3 MATK increase with every **upgrade above level 6**.

> Hercules Effect:
```
		if(getrefine() >= 6) {
			bonus2 bSkillAtk,SC_FATALMENACE,(getrefine()-5)*2;
			bonus bMatk,(getrefine()-5)*3;
		}
```

---------------------------------------

16010 - Red Ether Bag [1] :

> Korean: 해당스킬의 공격력은 6제련 시 부터 제련도 당 2% 씩 추가 증가.
> English: 20% ATK increase of Crazy Weed and Demonic Fire. 2% ATK increase of each skill for every **upgrade above level 6**.

> Hercules Effect:
```
		if (getrefine() >= 6) {
			bonus2 bSkillAtk, GN_CRAZYWEED_ATK, 20 + ((getrefine()-5)*2);
			bonus2 bSkillAtk, GN_DEMONIC_FIRE, 20 + ((getrefine()-5)*2);
		} else {
			bonus2 bSkillAtk, GN_CRAZYWEED_ATK, 20;
			bonus2 bSkillAtk, GN_DEMONIC_FIRE, 20;
		}
```

So, when uses sentence "8제련 시 부터 제련도 1당 AGI + 1 증가." can be interpreted as "starting from refine level 8, each aditional upgrade increases AGI + 1". It's like upgrade +8 be "level 0", and upgrade +9 be "level 1".

In that interpretation the items above are in error too, because effect should start at level 7, not level 6. But I don't have kRO account to test.

**Comment by Asheraf** [comment]
@iRagno Those items are correct according to aegis item db
```
item Black_Wing
	event OnStartEquip:
		var temp = GetRefineLevel [LOCATION_RARM]
		if  temp > 5
			AddDamage_SKID Target SC_FATALMENACE (temp - 5) * 2
			AddExtParam User VAR_ATTMPOWER (temp - 5) * 3
		endif
		AddDamage_SKID Target SC_FATALMENACE 30
	return
	event OnFinishEquip:
		var temp = GetRefineLevel [LOCATION_RARM]
		if  temp > 5
			SubDamage_SKID Target SC_FATALMENACE (temp - 5) * 2
			SubExtParam User VAR_ATTMPOWER (temp - 5) * 3
		endif
		SubDamage_SKID Target SC_FATALMENACE 30
	return
```
```
item Red_Ether_Bag
	event OnStartEquip:
		var temp = GetRefineLevel [LOCATION_RARM]
		if  temp > 5
			AddDamage_SKID Target GN_CRAZYWEED_ATK (temp - 5) * 2
			AddDamage_SKID Target GN_DEMONIC_FIRE (temp - 5) * 2
		endif
		AddDamage_SKID Target GN_CRAZYWEED_ATK 30
		AddDamage_SKID Target GN_DEMONIC_FIRE 30
	return
	event OnFinishEquip:
		var temp = GetRefineLevel [LOCATION_RARM]
		if  temp > 5
			SubDamage_SKID Target GN_CRAZYWEED_ATK (temp - 5) * 2
			SubDamage_SKID Target GN_DEMONIC_FIRE (temp - 5) * 2
		endif
		SubDamage_SKID Target GN_CRAZYWEED_ATK 30
		SubDamage_SKID Target GN_DEMONIC_FIRE 30
	return
```

**Comment by iRagno** [comment]
Then, the interpretation I give was wrong and effect starts on refine level 8.

As a reference, this is Peuz Greaves script on Auriga:

`2476,Pertz_Greaves,ペオースグリーブ,4,20,,900,,32,,1,128,2,64,,100,,1,{},{ bonus bMaxSP,40; if(getequiprefinerycnt(6) >= 8) bonus bAgi,getequiprefinerycnt(6)-7; }`

It gives +1 agi for every upgrade level starting at 8, and, taking consideration on previous examples, I think this is the correct one.
