### ISSUE TITLE
@refresh

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1549]
How to avoid this glitch?
1. Trade item to another player. Don't complete the trade yet.
2. type @refresh.
- you get the item and an extra item (duplicate).
- it reset to normal when you warp, relog.
I was wondering there might/could be a possible duplicate that may exit with this.

**Comment by Ridley8819** [comment]
If I remember correctly, this was an issue with old sakray clients?

**Comment by MishimaHaruna** [comment]
As far as I'm aware it's just a visual issue in the client, and doesn't cause any actual item duplication. The way I remember it, though, required the other side to abort the trade after the refresh (but I may be wrong here).

The issue occurs because the client loses track of the items in the trade window when it gets suddenly teleported (which is what `@refresh` does). I'm not sure if there's a way to work around this.

I don't personally recommend to enable `@refresh` as a player command on a Ragnarok server, since I consider it a very ugly hack, and I know that it causes all sorts of nasty glitches.

**Comment by Ridley8819** [comment]
closing this. Can be reopened if there is ever the need to :)
