### ISSUE TITLE
HPMdata error when compiling

### ISSUE THREAD

**Issue by Mojacko** [HerculesWS/Hercules#1834]
I am using the latest version of Hercules.

Description:
i just updated my server into latest a while ago and after i try to compile this error showing.
http://imgur.com/a/7Wo0s

Current behavior:
I cannot proceed with the compilation

Expected behavior:
cannot start server

Steps To Reproduce The Issue:
I just updated my server files into latest version of hercules (8/30/17)

Master branch

Git hash: 7c2f6afe542bf42f1c527877bde082274c473f29

CentOS 6 64bit

**Comment by Asheraf** [comment]
Hello there, please follow the issue opening template and reopen your issue.

https://github.com/HerculesWS/Hercules/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Mojacko** [comment]
I have edited it

**Comment by Asheraf** [comment]
Missing the git src hash

**Comment by Mojacko** [comment]
hi sorry editted it again with git hash

**Comment by 4144** [comment]
after major update code like this, you must clean data and build from scratch.
in other words run:
```
make clean
./configure
make
```
And show error if it still present

**Comment by Mojacko** [comment]
Hi @4144  i did what you said and it gives me this error
http://imgur.com/a/mlSZt

**Comment by 4144** [comment]
Show output of this commands:
```
gcc --version
git status
```

**Comment by Mojacko** [comment]
@4144  gcc version = http://imgur.com/a/SLptQ
git status = http://imgur.com/a/TMDxu

i forgot to mention that i have gepard.

**Comment by 4144** [comment]
hm, too many files changes. and build error show what some code look like broken.
Probably better ask support from gepard devs.

**Comment by 4144** [comment]
another thing. Look like you using too old gcc. Try install newer version.

**Comment by MishimaHaruna** [comment]
Also please note that GCC 4.4 on CentOS 6 isn't a supported compiler, as it some times shows incorrect error messages if it runs out of memory.

To compiler Hercules on CentOS 6, we recommend to upgrade GCC to version 4.7 or newer, as mentioned in the [Supported Platforms](https://github.com/HerculesWS/Hercules/wiki/Supported-Platforms#centos-and-red-hat-enterprise-linux) wiki page.
This is available through the [devtoolset-3](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/) (or newer), although I'd consider updating to a more recent version of the OS, especially since CentOS 7 was released over 3 years ago.

Please note that this is just a recommendation based on past tests, and it may not help solving the problems, if there are actual incompatibilities with the custom modifications you have in your source.

**Comment by Mojacko** [comment]
I tried to update my gcc to 4.9 but it still give me the same error :o 
http://imgur.com/a/uhior

int_storage.c:241

**Comment by 4144** [comment]
this error look like bad patch from gepard. Ask them about compilation errors.
