### ISSUE TITLE
svn checkout

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1897]
-  [x ] I have not modified the source prior to reproducing this issue.
-  [ x] I am using the latest version of Hercules.
-  [ x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

why i cant fetch newer updates using svn checkout?
last changes on https://github.com/HerculesWS/Hercules was 13 days ago. Those committed after that  is not yet merge?

**Comment by MishimaHaruna** [comment]
The use of SVN to obtain the Hercules sources isn't recommended, since we have no control over it. Please consider switching to git.

To my understanding, github only offers the default branch to the svn users, and we switched the default branch to 'stable' (which is the version we encourage to use in production servers). The last commit on the stable branch is indeed from 13 days ago (release `v2017.10.22-1`)
