### ISSUE TITLE
Buff Skill Not Working after update.

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1911]
-  [ x] I have not modified the source prior to reproducing this issue.
-  [x ] I am using the latest version of Hercules.
-  [ x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
- angelus, gloria, adrenaline rush, angelus etc.

**Comment by Nurkz** [comment]
#1909

**Comment by Nurkz** [comment]
#1909 there is explanation
@MishimaHaruna @4144

**Comment by MishimaHaruna** [comment]
Do you have any additional details? #1910 was supposed to have fixed this

**Comment by Nurkz** [comment]
@MishimaHaruna it happens when `party->foreachsamemap` got `< 0` in third parameter,
in old rev was a check for `skill_splash >= 0 ? skill_splash : AREA_SIZE;`, in you patch it just return `skill_splash` as it is.

for example angelus in `db/pre-re/skill_db.conf` have `-1` Splash area
![image](https://user-images.githubusercontent.com/15338159/33234201-3af420f6-d22b-11e7-871f-bde4d4016665.png)

**Comment by MishimaHaruna** [comment]
Thank you, I opened #1914 with a fix for this
