### ISSUE TITLE
MvP Tomb Spawntime

### ISSUE THREAD

**Issue by changelets** [HerculesWS/Hercules#1980]
"On official servers MvP Tombs spawn a few seconds after the MvP is killed.

On rathena (Hercules) the MvP Tomb spawns immediately. So sometimes it's kinda hard to loot dropped Items near the tomb."

By Jeybla.

Link: https://github.com/rathena/rathena/issues/1429

**Comment by mrjnumber1** [comment]
Tombs in Aegis in general are bugged anyways!

It's true that they spawn a few seconds after the MVP dies, but oddly they're a dynamically created NPC every time. 
There is a timer set every 10 seconds if an MVP is alive on any map, if it is, it will remove the tomb.

But, a bug exists such that the MVP could respawn just after the check, *and* be killed before the next check. This is why you see situations such as in prt_sewb4 where there are multiple MVP tombs sitting around, because so many people are camping it.
