### ISSUE TITLE
@fakename

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#2539]
**Describe the bug**
@.fakename is not working

 - Hercules Version [v2019.09.22]

**Comment by 4144** [comment]
why closed? it works?

**Comment by kyeme** [comment]
Sorry I accidentally closed it.

**Comment by 4144** [comment]
and how it not works? what happend if enabled fake name?

**Comment by bWolfie** [comment]
This is happening due to lines
`if (ssd->fakename[0] != '\0' && ssd->disguise != -1) {`

Previously we didn't check for `ssd->disguise != -1`. ssd->disguise will always be -1 if the player isn't using any disguise, so this needs to be fixed.

I'm not sure why fakename needs to check for disguise, AFAIK there have been no reports of disguise having bad interactions with fakename.
