### ISSUE TITLE
Fireproof Potion Timer

### ISSUE THREAD

**Issue by feltenc** [HerculesWS/Hercules#2593]
**Describe the bug**
When using the Fireproof Potion the timer dont disappear and turns into negative.

Item:

**To Reproduce**
1. @item 12118
2. Use the item
3. Check the timer

**Expected behavior**
When the timer ends the icon should disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/22537929/70283070-a47abc00-179e-11ea-84da-df1ea1dc22cd.png)
![image](https://user-images.githubusercontent.com/22537929/70283021-82813980-179e-11ea-8d40-0e1dfd0c84b2.png)

**System specs (please complete the following information):**
 - OS: Windows 7(tested on w10 too).
 - Git HASH 75ae018
 - Mode: Pre-re
 - Packet version: 20180621a
 - Client type: RE

**Plugins used or source modifications**
none

**Additional context**
none

**Comment by Kenpachi2k13** [comment]
I can confirm this. Seems to be a problem with `SC_ARMORPROPERTY`.
When using `SC_ARMORPROPERTY` in `sc_start()` or `sc_start2()`, the same issue occurs.
I'll investigate this.

**Comment by Kenpachi2k13** [comment]
Okay, problem spotted.
In `status_change_end_()` `clif->sc_end()` is called for `SC_ARMORPROPERTY`. This has no effect because this status change was never send to the client.
Actually one or more of these status changes needs to be ended client side: `SC_RESIST_PROPERTY_WATER`, `SC_RESIST_PROPERTY_GROUND`, `SC_RESIST_PROPERTY_FIRE`, `SC_RESIST_PROPERTY_WIND`

Changing the item script to:
```
sc_start(SC_RESIST_PROPERTY_FIRE, 1200000, 20);
sc_start(SC_RESIST_PROPERTY_WATER, 1200000, -15);
```
would work as expected, but then 2 status icons are shown and I don't know if official servers display 1 or 2 status icons.
The official item script separates the 2 status changes, but as mentioned above, I don't know if both icons are displayed.
```
item Resist_Fire
	event OnConsume:
		SubDamageTM_Prop	User	PROPERTY_Fire	20	1200
		AddDamageTM_Prop	User	PROPERTY_Water	15	1200
	return
```

**Comment by Kenpachi2k13** [comment]
As far as I was able to figure out, the 4 elemental resistance potions display only the icon for the increased resistance.
Additionally Undead Elemental Scroll should display all 4 icons instead of no icons, since it uses `SubDamageTM_Prop`, too.
