### ISSUE TITLE
ALL_RESURRECTION,1 Bug

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2646]
**Describe the bug**
item ID# 610 (Leaf_Of_Yggdrasil) when use it ask for GEMSTONE

OS: Centos7 64x
Hercules Version latest git
Mode: PRE-RE
Packet version: 20150429
Client type: main

**Comment by tlacson7** [comment]
@dastgirp can you check on this sir?

**Comment by Kenpachi2k13** [comment]
The skill itself is correct. The actual problem is the `itemskill()` script command, which was modified by me in #2600.
Before that PR was merged, all skills which were cast by `itemskill()` script command, ignored all conditions/requirements. The reason to change this behaviour can be seen in the [first commit](https://github.com/HerculesWS/Hercules/pull/2616/commits/1098b588625774ca2cf4e05527b00fd4d0187919) of that PR.

The bug report, mentioned in the commit message, is valid, since `CP_Helm_Scroll` and other chemical protection scrolls check for the skills requirements and also consume them in AEGIS. (The only exception is SP consumption.)

I tested `Leaf_Of_Yggdrasil` in AEGIS and it really ignores the requirement of the `Blue_Gemstone`.

In AEGIS both items, `CP_Helm_Scroll` and `Leaf_Of_Yggdrasil`, use the same command to cast the skill:
```
item Leaf_Of_Yggdrasil
	event OnConsume:
		Skill	ALL_RESURRECTION	1
	return


item CP_Helm_Scroll
	event OnConsume:
		Skill	AM_CP_HELM	5
	return
```

I have to investigate why one checks for the skills requirements and the other one does not. Currently I'm a little bit baffled. :confused:

**Comment by tlacson7** [comment]
`For now I suggest to change the item script to:
itemskill(ALL_RESURRECTION, 1, ISF_IGNORECONDITIONS);`
yes it did work.

**Comment by tlacson7** [comment]
@Kenpachi2k13 sorry sir , 
itemskill(ALL_RESURRECTION, 1, ISF_IGNORECONDITIONS); still requires gemstone.
1. without adding ISF_IGNORECONDITIONS, when you use yggleaf it will give you "Blue Gemstone required".
2. adding ISF_IGNORECONDITIONS, when you use yggleaf it will work but when you aim your cursor to dead player, it will then ask the gemstone.

For your information :D

**Comment by Kenpachi2k13** [comment]
Yeah, I noticed this yesterday while working on a clean up of all the different auto-casts flags/states we currently use.
I'm not sure if this will be finished until the next release (v2020.08.03), so for now you could use the quick'n'dirty fix below.

 * In src/map/unit.c find these two functions:
   * `unit_skilluse_id()` (Line 1042.)
   * `unit_skilluse_pos()` (Line 1679.)
 * In both functions replace `if (sd != NULL)` with `if (sd != NULL && !skill->is_item_skill(sd, skill_id, skill_lv))`

**Comment by zgmfx20b** [comment]
Butterfly wing and flywing still failed most of the time.

**Comment by Kenpachi2k13** [comment]
@zgmfx20b 
Please open a new issue instead of resurrecting one which isn't related to Fly Wings or Butterfly Wings.
Also please provide some information. Does your server version contain this pull request: #2657?
Did you already try this pull request: #2699?
Any details on the circumstances when these items fail executing the skill?
