### ISSUE TITLE
nullpo

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2707]
**Describe the bug**
(05/03/2020 02:32:33) [ Error ] : --- nullpo info --------------------------------------------
(05/03/2020 02:32:33) [ Error ] : unit.c:273: 'tbl' in function `unit_steptimer'
(05/03/2020 02:32:33) [ Error ] : 0x630786 nullpo_backtrace_print
(05/03/2020 02:32:33) [ Error ] : 	/home/lagyserver/Hercules/src/common/nullpo.c:77
(05/03/2020 02:32:33) [ Error ] : 0x630786 assert_report
(05/03/2020 02:32:33) [ Error ] : 	/home/lagyserver/Hercules/src/common/nullpo.c:147
(05/03/2020 02:32:33) [ Error ] : 0x61a91e unit_steptimer
(05/03/2020 02:32:33) [ Error ] : 	/home/lagyserver/Hercules/src/map/unit.c:273
(05/03/2020 02:32:33) [ Error ] : 0x63b388 do_timer
(05/03/2020 02:32:33) [ Error ] : 	/home/lagyserver/Hercules/src/common/timer.c:498
(05/03/2020 02:32:33) [ Error ] : 0x408d02 main
(05/03/2020 02:32:33) [ Error ] : 	/home/lagyserver/Hercules/src/common/core.c:538
(05/03/2020 02:32:33) [ Error ] : 0x7fb6b24c7504 ???
(05/03/2020 02:32:33) [ Error ] : 	???:0
(05/03/2020 02:32:33) [ Error ] : 0x408ed2 ???
(05/03/2020 02:32:33) [ Error ] : 	???:0
(05/03/2020 02:32:33) [ Error ] : 0xffffffffffffffff ???
(05/03/2020 02:32:33) [ Error ] : 	???:0
(05/03/2020 02:32:33) [ Error ] : --- end nullpo info ----------------------------------------

**To Reproduce**
Don't know how to reproduce. I saw in log, many of those entry.

**System specs (please complete the following information):**
 - OS: Centos 7 x64
 - Hercules Version latest
 - Mode: pre-renewal
 - Packet version: 20151029
 - Client type: main

**Plugins used or source modifications**
no

**Comment by Kenpachi2k13** [comment]
@skyleo (Since you introduced this in #2546 I'm addressing you.)
I'm not sure if a `NULL` pointer report really is a good choice here since a `block_list` can be destroyed in quite a number of different situations. So it's kind of expectable to occasionally be unable to retrieve it by its ID. If it were passed directly I would agree to report the `NULL` pointer, but in this case I suggest to switch back to simply return an error code like it was handled before.

**Comment by tlacson7** [comment]
this still reporting on the latest build.
