### ISSUE TITLE
SC_DANCING is missing skill unit group

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#2716]
**Describe the bug**
(05/09/2020 14:39:22) [ Debug ] : status_change_end: SC_DANCING is missing skill unit group (val1=655681, val2=49623, val3=122, val4=0, timer=1143, tid=-1, char_id=14729, map=aldebaran, x=143, y=107, prev=<none>:0, from=unit.c:2581). Please report this! (#3504)

(05/09/2020 14:39:24) [ Debug ] : status_change_end: SC_DANCING is missing skill unit group (val1=655681, val2=50005, val3=169, val4=0, timer=1330, tid=-1, char_id=14985, map=payon, x=72, y=102, prev=<none>:0, from=skill.c:7280). Please report this! (#3504)

(05/09/2020 14:39:28) [ Debug ] : status_change_end: SC_DANCING is missing skill unit group (val1=655681, val2=49777, val3=121, val4=0, timer=502, tid=-1, char_id=12747, map=aldebaran, x=143, y=106, prev=<none>:0, from=unit.c:2581). Please report this! (#3504)

**System specs (please complete the following information):**
 - OS: Centos 7 x64
 - Hercules Version Latest
 - Mode: pre-re
 - Packet version: 20151029
 - Client type: main

**Comment by Kenpachi2k13** [comment]
`char_id=14729` `char_id=14985` `char_id=12747`

Did you intentionally enable character IDs lower than 150000?

**Comment by tlacson7** [comment]
@Kenpachi2k13 not intentional , it happened when i empty the char table and player created started to 1. i did not rollback but change starting char# at mmo.

**Comment by Kenpachi2k13** [comment]
I had a look at this and I don't think this is an issue related to Hercules.
In all 3 debug messages you posted the value of `val1` is `655681`. `val1` holds a skill ID and there is no such skill ID in Hercules.
Furthermore `val3` looks weird, too. It holds a skill level and in all 3 debug messages it's much greater than 100...

In my opinion this issue is caused by modifications.
