### ISSUE TITLE
Runtime error on KO_GENWAKU SC effect

### ISSUE THREAD

**Issue by MrKeiKun** [HerculesWS/Hercules#2832]
**Describe the bug**
After introducing #2831, console returned a warning. Regarding `SC_CONFUSION` effect regarding randomized target cell.

**To Reproduce**
1. Use #2831 PR.
2. Configure and Build Hercules with `--enable-manager=no --enable-sanitize=full`
2. Try using `KO_GENWAKU` to any target

**Logs**
`map.c:2974:20: runtime error: -nan is outside the range of representable values of type 'short int'`
**System specs (please complete the following information):**
 - OS: CentOS 8 x64
 - Hercules Version: master branch
 - Mode: renewal
 - Packet version: 20180418
 - Client type: RE

**Comment by skyleo** [comment]
that line is `segment = (short)sqrt((float)(dist2 - segment*segment)); //The complement of the previously picked segment`
Means that (dist2 - segment*segment) is a negative number, which unfortunately doesn't get cought from the function. And can happen for example when dist < 1 so dist = 1 but dist2 will be 0, while segment will be 1. so it's -1 to be specific.

Your change must have caused this somewhere due to incorrect arguments passed.

**Comment by MrKeiKun** [comment]
After September 2020 release, the runtime error never showed back after 20x reproducing the problem. I'm not sure if the problem is fixed(Not sure how).
