### ISSUE TITLE
about emistry's mercenary_delete PR ...

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2843]
damn, I was slow to [check this PR](https://github.com/HerculesWS/Hercules/pull/2818)

1. this documentation only says 2 value, but actually there are 4
https://github.com/HerculesWS/Hercules/blob/1354b01c7a24e9ffd9ea570cbaec668721fc2a6c/src/map/clif.c#L18778-L18789

2. usually the `<char id>` or `<gid>` put at the end of the script command if it is optional value
`*mercenary_delete({<update>, <char ID>})`

3. and if needs to add constant for it, should done in mercenary.h,
then every source code with mercenary->delete needs to update the value into constant along with it

now what ... too slow, too busy with paid request ...

PS: I couldn't post any message on that PR, 
https://github.com/AnnieRuru/customs/blob/master/screenshots/cannot_comment_after_merge.png
so I open an issue for the time being

------------------------------------

also I notice a ridiculous `@inventorylist` inside `*getcartinventorylist`
https://github.com/HerculesWS/Hercules/blob/1354b01c7a24e9ffd9ea570cbaec668721fc2a6c/doc/script_commands.txt#L3232-L3252

when I have time need to check 1 by 1

**Comment by AnnieRuru** [comment]
stupid unicorn, saying page takes too long to load

**Comment by AnnieRuru** [comment]
@MishimaHaruna is it still possible to [revert this PR](https://github.com/HerculesWS/Hercules/pull/2818) for now ?

**Comment by Emistry** [comment]
1. that is just purely for message display. `mercenary->delete(...)` and `clif->clif_mercenary_message(...)` aren't the same.

2. that's not entirely true (check `*unitkill(...)` and etc) , anyway position of `char_id` or `gid` as the last parameter are debatable.
Imo, adding `char_id` or `gid` as last parameter kill the possibility to expand the script command in future, we had this debate in the past while trying to figure out a way to expand `getitem2/3/4/5` due to the position of each param.

**Comment by AnnieRuru** [comment]
1. proved in screenshot
https://raw.githubusercontent.com/AnnieRuru/customs/master/screenshots/mercenary_delete.png

2. getmercinfo(<type>{, <char id>})
there are already existing scripting command with similar layout, and it's also under mercenary type

**Comment by Emistry** [comment]
thank for that, will update it later.
