### ISSUE TITLE
*rodex_sendmail script command can send with non-existent char ID

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2898]
**Describe the bug**
1. you can use script command to send a mail to non-existent char ID
2. if send using the script command below will cause char-server.exe spam failed assertion

```
[Error]: --- failed assertion --------------------------------------------
[Error]: F:\Ragnarok\Hercules\src\char\mapif.c:1734: 'receiver_id + receiver_accountid > 0' in function `mapif_rodex_send'
[Error]: --- end failed assertion ----------------------------------------
```

**To Reproduce**
```c
prontera,155,185,5	script	kjsdfhks	1_F_MARIA,{
	rodex_sendmail 123, "someone", "title", "body\r leg", 0, Apple, 1; // send successfully and produce a line in `rodex_mail` table
	rodex_sendmail getcharid(CHAR_ID_CHAR, 0), "someone", "title", "body\r leg", 0, Apple, 1; // failed assertion
}
```

**Expected behavior**
1. not sure if its possible to use `char` table to check if the char ID is non-existent
but I think it can be work as intended as it's scripter's fault to send to wrong char ID

.... PS: however try send a mail normally, there is a validate name button to forbid sending to non-existent char though

2. failed assertion is another thing, this should be fixed

**System specs (please complete the following information):**
 - OS: Windows 10 pro 64-bit
 - Hercules Version: latest (always pull latest git)
 - Packet version: 20190530
 - Mode: Renewal
 - Client type: [2019-05-30aRagexeRE](http://nemo.herc.ws/downloads/2019-05-30aRagexeRE/)
 - Branch: Main

**Plugins used or source modifications**
................

**Additional context**

**Comment by Kenpachi2k13** [comment]
The problem is `rodex_sendmail_sub()` (script.c) blindly takes the receiver's character/account ID from the argument passed by the script command without doing any evaluation.
```c
	if (strcmp(script->getfuncname(st), "rodex_sendmail_acc") == 0 || strcmp(script->getfuncname(st), "rodex_sendmail_acc2") == 0)
		msg->receiver_accountid = script_getnum(st, 2);
	else
		msg->receiver_id = script_getnum(st, 2);
```

To make this process safer `script_getnum(st, 2)` should be checked against `START_CHAR_NUM` respectively `START_ACCOUNT_NUM`/`END_ACCOUNT_NUM` prior to assigning the receiver's character/account ID.


> not sure if its possible to use char table to check if the char ID is non-existent

This would require a new inter server communication packet because the character data should only be accessible by the character server. In my opinion that's too much effort for a small benefit.
