### ISSUE TITLE
Attack range in skills - distance to target

### ISSUE THREAD

**Issue by vthibault** [HerculesWS/Hercules#307]
I notice while testing roBrowser than the skills attack range sent to the client doesn't match the maximum distance a player can cast a skill to a target.

Let me explain :
The server send a `attackRange` property for each skill when sending the skill list.
- Player want to cast a skill.
- Client check the distance, if distance is more than the attackRange, move to the nearest point
- then cast the skill.

I noticed that you could, by cheating the client (hook/proxy/...), move one cell away and be able to cast the skill too (the server allow a `attackRange+1` distance while doing the distance check).

Is it the correct behavior ? Trust the client and maybe keep a +1 cell in case of precision error / lag ?

**Comment by Playtester** [comment]
That's more of a roBrowser issue.

Ranges in the official client work a bit strange, especially for players, because the range is circular for players but with an increased range of 1. Also notable, you can only make use of max range if you are standing still on a cell inside the range. If you are moving or if you are targetting from outside your range you will move one cell closer than you need to.

Gravity probably intentionally implemented this to prevent the issue that a skill casting keeps failing because the target is moving.

I made a graph once to illustrate how ranges work on official servers:
https://rathena.org/board/uploads/monthly_10_2014/post-14651-0-49007200-1412429154.png
