### ISSUE TITLE
Soul Linker Class returns null bl in skills

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#3145]
Something I noticed when testing with CG_TAROTCARD.

When (eff == 2), which is High Priestess card (remove all buffs), was used on a Soul Linker, buffs would not be removed. I added some ShowDebug clauses to the top of  `status_change_clear_buffs` and it wouldn't even register.
```
					case 2: // all buffs removed
						status->change_clear_buffs(bl,1);
						break;
```

Then when I changed it to:
```
					case 2: // all buffs removed
						if (sd != NULL)
							status->change_clear_buffs(&sd->bl,1);
						else
							status->change_clear_buffs(bl, 1);
						break;
```

It did work and removed all buffs. I don't know what is causing this interaction to happen like this.

**Comment by MrKeiKun** [comment]
What buffs are you trying to clear? I tested with `SC_INCAGI` and `SC_BLESSING` buffed on the Soul Linker, works fine.

**Comment by bWolfie** [comment]
I used a Blessing Scroll.

**Comment by MrKeiKun** [comment]
Okay so instead of using `@useskill`, I used `Blessing_10_Scroll` and this is Renewal btw.

On Buff:
![image](https://user-images.githubusercontent.com/4362134/174300322-4790fa6a-50cb-4a3e-90fc-941c01ccd58e.png)

On Tarot Cast:
![image](https://user-images.githubusercontent.com/4362134/174300549-b28a4fd1-014f-4067-9b96-3fd6a66affe2.png)

**Comment by bWolfie** [comment]
Sorry must be custom code. Closing.
