### ISSUE TITLE
@duel / Infinite Songs

### ISSUE THREAD

**Issue by Streusel** [HerculesWS/Hercules#546]
Step 1: Clown will cast the song with the player or without the player in it's AoE
Step 2: The Clown will type "@duel" (no name)
Step 3: The player will now then leave the AoE of the song
Step 4: Once the player is out of range the AoE of the song, the Clown will now type "@leave"

Or refer to this post: http://herc.ws/board/tracker/issue-8582-duel-infinite-songs/

**Comment by anacondaqq** [comment]
at rathena this bug as i remember already fixed. i do not remember, is it fixed at herc too.

**Comment by Streusel** [comment]
Well I got the report today that it is still possible to recreate this, and that is with the latest hercules. So I'll assume it still is possible. Also I don't see why kyeme would else keep bumping it.

**Comment by AnisotropicDefixation** [comment]
It was fixed partially but there are still way to exploit it (even on rA), it's been years and nobody managed to fully deal with this issue.

What I did myself was add SC_DANCING checks for the @duel atcommand, no issues so far.

**Comment by kyeme** [comment]
@Streusel thanks!

@MishimaHaruna :D

**Comment by kyeme** [comment]
:[

**Comment by GrumpyLittlePanda** [comment]
It was fixed https://github.com/HerculesWS/Hercules/commit/145a4fe644c4fe856ba6f83086e8ee5075caad99, It seemed to work fine after the first fix from what I tested. However it was broken again the same day.
https://github.com/HerculesWS/Hercules/commit/127f9b52a4030a655564584b95b7c10dfdcb04e6

Not sure what situation that else if is needed for as mordekaisers scenario is not explained anywhere. 

However onsidering songs if source master is in a duel group x and target is not the song will not cancel upon leaving the area because skill->unit_onleft does not get triggered due to battle_check_target returning 0.

**Comment by MordekaiserGod** [comment]
My scenario is much more devastating than this current bug. If you are able to target anything (including monsters) during @duel, then there is no reason to leave a duel. Therefore infinite provoke and mindbreaker is granted.

The best fix I see for this is put back commit 145a4fe, remove my scenario fix in 127f9b5, make duel defaulted to towns only, and pray no one abuses hocus pocus in towns with provoke/mindbreaker.

**Comment by kyeme** [comment]
@MishimaHaruna master pls :D

**Comment by kyeme** [comment]
Up~

**Comment by kyeme** [comment]
~ Up ~
