### ISSUE TITLE
Spear Dynamo/Concentration ending when Frenzy/Berserk is used

### ISSUE THREAD

**Issue by Streusel** [HerculesWS/Hercules#556]
Very self explanatory title.
1. Use Spear Dynamo/Concentration (LK)
2. Use Frenzy/Berserk (LK)
3. The buff that Spear Dynamo/Concentration provides and should last up to 45 seconds disappears.

There is a mention in it here: https://github.com/rathena/rathena/commit/62a2813 not sure if it was merged or not, or if it broke again since then.

**Comment by dastgir** [comment]
That was merged, maybe something else broke it.

**Comment by MishimaHaruna** [comment]
It wasn't really merged, was it?

See the `case SC_ENDURE` in their commit's status.c, line 7922 - we still have that block. (around line 7324 of status.c)
I'm not sure if removing it would have any side effects, since its purpose wasn't clear when it was added in commit 03956104 2 years ago (i.e. I'll never stop saying that those large commits are like a time bomb and never fail to deliver at some point in the future), and there might have been some other updates in the meanwhile that rely on it.

Can @malufett or @Michieru look into this?

**Comment by dastgir** [comment]
I am blind :see_no_evil:

**Comment by malufett** [comment]
Fixed @ 408e8ce47ec298b80e43b537efa58db5b74a19b8
