### ISSUE TITLE
kick vendor in autotrade mode crashes map server

### ISSUE THREAD

**Issue by Angelmelody** [HerculesWS/Hercules#568]
long story short ,when npc script attach a @at state vendor then kick him map server will go crashed,but if npc script doesn't attach @at state vendor ,kick command was working fine..
Here are my test scripts:

<pre><code>
prt_fild08,174,367,5    script  kick@ATvendor   100,{
    input.@name$;
    query_sql("SELECT `account_id` FROM `char` WHERE `name` = '"+escape_sql(.@name$)+"'", .@aid);
    attachrid(.@aid); 
    atcommand "@kick "+strcharinfo(0);
    end;
}
</code></pre>

<pre><code>
prt_fild08,174,362,5    script  kick@ATvendor2  100,{
    input.@name$;
    query_sql("SELECT `account_id` FROM `char` WHERE `name` = '"+escape_sql(.@name$)+"'", .@aid);
    //attachrid(.@aid);
    atcommand "@kick "+rid2name(.@aid);
    end;
}
</code></pre>

**Comment by MishimaHaruna** [comment]
Even without seeing a crash backtrace, this seems the same issue as http://herc.ws/board/tracker/issue-8594-mapserver-crash/?gopid=24850#entry24850

The more I think about it, the more I feel that the issue here is conceptual. Attaching a script to a character that isn't connected (an autotrader), is a pretty awkward thing, and I'm debating whether we should put some band aid (some workaround that detects cases like this and defer the script state deallocation), we might want to prevent the issue from happening altogether by disallowing to attach a dummy RID (such as a character that's not associated to a client). After all, a large number of script commands expect that, if they have a RID attached, they also have a client attached (mes, next, select, etc).

**Comment by vBrenth** [comment]
Bump! ->

**Comment by vstumpf** [comment]
Any clue when this will get fixed? It's an easily reproducible server crash that can hurt any private server using Herc.

**Comment by MishimaHaruna** [comment]
While I agree with "easily reproducible", I disagree with "that can hurt any server". The very easy workaround for a server owner is to avoid running a poorly designed script that attaches to a character in autotrade mode and kicks it, no?

**Comment by vstumpf** [comment]
You can take a merchant and autotrade on the airship and vend on top of the warp that opens every ~2 minutes.
