### ISSUE TITLE
According to iRO, Zenkai Skill bug on hercules

### ISSUE THREAD

**Issue by Helheim90X** [HerculesWS/Hercules#607]
A guy has posted this in the old issue track of hercules's forum...
here is what he says:

Zenkai checking interval is less than 1s and causing all ailments at same time. [2nd part needs checking against Aegis or more sources]

Source(s):
http://irowiki.org/w...ast_Ninja_Spell
http://forums.warppo...-success-rates/

https://www.youtube.com/watch?v=mSXPkC7y-Vo

Current interval code in Herc github:
3020,0xf8, , 0, 3, 100,all, 0x018 //KO_ZENKAI //This is 0.1s check

Current interval code in rA github:

3020,0xf8, , 0, 2, 500,all, 0x018 //KO_ZENKAI //This is 0.5s check

interval Fix maybe:
3020,0xf8, , 0, 3, 1000,all, 0x018 //KO_ZENKAI // This is 1s check

Could be nice of you if set this as a merge on master track.
Or in anycase, could check the skill.

**Comment by Inzianity** [comment]
Oh great was supposed to create an issue here to follow up my report. Thanks for making it.
So yeah, here's a link to the original report http://herc.ws/board/tracker/issue-8532-kagerou-oboro-skill-zenkai-checking-interval-is-less-than-1-second-and-causing-all-ailments-at-the-same-time/
Core dev already responded to it so some fully up would be really great since it's so broken with a 10th of a second interval between checks.

**Comment by MishimaHaruna** [comment]
@malufett what's the correct fix here according to aegis? Setting the skill unit's interval to 500ms?

**Comment by malufett** [comment]
@MishimaHaruna 
"Setting the skill unit's interval to 500ms?"
yep

**Comment by BugCityBoiz** [comment]
Any updates on this issue?
Experiencing the same problem too
