### ISSUE TITLE
Mapflag novending problem

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#662]
Hi!

If you set a novending mapflag in a map, and you use the skill Vending. After you click ok, your character will stuck up. Please confirm. thanks!

**Comment by Jedzkie** [comment]
Bump?

**Comment by AnnieRuru** [comment]
### Issue Prelude
-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Vending Skill cause player to get stuck if press the Cancel button

### Current Behavior
using Latest Hercules,, after Cancel the Vending window, the player gets stuck

### Expected Behavior
tested on rathena however, it display a message immediately using the skill
`You can't open a shop on this cell`

### Steps To Reproduce The Issue
```
-	script	Test	FAKE_NPC,{
OnInit:
	setcell "prontera", 0,0, 500,500, cell_novending, true;
}
```
1. change job into merchant
2. Alt + S to open skill window
3. double-click the vending skill
4. the vending window ask you to input shop name
5. press Cancel button
6. and ... your character stuck


### Branch(es):
- [x] master

### Hercules rev. hash/commit: & Operating System
```
[Info]: Hercules 32-bit for Windows
[Info]: Git revision (src): 'fc175850efdb4dd258dd8bbab4b01be8f1c327fa'
[Info]: Git revision (scripts): 'fc175850efdb4dd258dd8bbab4b01be8f1c327fa'
[Info]: OS version: 'Windows 7 Ultimate Service Pack 1 (build 7601) [x86]'
[Info]: CPU: 'x86 CPU, Family 6, Model 23, Stepping 10 [2]'
[Info]: Compiled with Microsoft Visual C++ 2015 (v1900)
```

urgh ... luckily I search before post, so yeah bump
