### ISSUE TITLE
Warning when creating instance dungeon

### ISSUE THREAD

**Issue by belfallen** [HerculesWS/Hercules#693]
Using lastest revision..

![zxc](https://cloud.githubusercontent.com/assets/5786514/9670811/ab7f518c-52b8-11e5-8723-70387de87f45.jpg)

**Comment by belfallen** [comment]
npc base in file already use contants but still appear this warning :(

alexa_in,82,155,3	script	Guild Manager	1_M_LIBRARYMASTER,{

**Comment by AnisotropicDefixation** [comment]
Just comment the warning, line 2539 in npc.c.

**Comment by emistry** [comment]
Change your NPC ID number into a  NPC Constant.

NPC ID 945 = 4_M_DST_GRAND
http://nn.nachtwolke.com/dev/npclist/?q=945&qq=search

**Comment by dastgir** [comment]
@Emistry, what's interesting is file name and line

@MishimaHaruna , what's with those random name and line?

**Comment by MishimaHaruna** [comment]
This is happening because of how `npc_duplicate4instance` works... It calls `npc->parse_duplicate`, passing a buffer with a `duplicate()` NPC header forged for the purpose.

It'll need some refactoring. We can use the values directly, instead of writing to a buffer and parsing them again as a string (it'll be also faster and less subject to errors...)

**Comment by MishimaHaruna** [comment]
This was fixed through #820
