### ISSUE TITLE
Error in new maps

### ISSUE THREAD

**Issue by xBeret** [HerculesWS/Hercules#801]
The new maps of the KRO are in trouble while doing the mapcache because the name of the map is greater than 12 characters, then the cache is not done.

prt_church_evt

Link Hercules: http://herc.ws/board/tracker/issue-7703-error-in-the-mapcache-of-new-maps/

**Comment by dastgir** [comment]
@xBeret, any way to reach those map in kRO, I would like to see if its accessible and if they use some other packets for those...

**Comment by xBeret** [comment]
@dastgir I have no idea.

**Comment by Ridley8819** [comment]
@hemagx

**Comment by hemagx** [comment]
We may add support for longer names, however i don't think this will be any wise until we figure out if this limit  can be used in anyway with the client.
@MishimaHaruna

**Comment by MishimaHaruna** [comment]
I believe that (until proven otherwise) any maps with longer names were mistakes while building the GRF (it's not like they never did mistakes, then re-added the same files with the correct names)

Like Ind said in the linked topic, those maps appear to be warpable to just by coincidence (because prt_church_evt gets trimmed to prt_church which is a valid value (and, again by coincidence, it's a resnametable copy of the intended map). If any of those conditions is different, unexpected things may happen.

The client packet is not designed to use longer names, and until it is, I don't think there's a point in supporting them. If official servers start using those maps, then it's different.

**Comment by xBeret** [comment]
Well the cache is not done by these maps are copies of others, the problem here is that the file map_index.txt and maps.conf does not accept the size of the map name, and it is necessary to add to use teleportation for example
