### ISSUE TITLE
Unable to use AegisName as constant  if it contain full stop symbol

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#830]
```
prontera,156,178,5  script  sdkfdsjf    1_F_MARIA,{
    dispbottom "Mob ID: "+ DEVIRUCHI +" | Egg ID: "+ Deviruchi_Egg; // OK
    dispbottom "Mob ID: "+ BAPHOMET_ +" | Egg ID: "+ Bapho_Jr._Egg; // error
}
```

immediately get an error from map server

.

use Regular Expression to find with Notepad++ inside item_db.conf

```
AegisName: "[a-z0-9_]*\.
```

return about 7 results

**Comment by dastgir** [comment]
Seems Script unable to recognize . in constant

**Comment by MishimaHaruna** [comment]
I knew this was gonna bite us eventually. Self assigning, I'll take care of this.

**Comment by MishimaHaruna** [comment]
Interestingly, there are some items with other unusual characters in their name:

```
AegisName: "Thanatos_Two-Handed_Staff"
AegisName: "True_Howard_Alt-Eisen_Card"
AegisName: "Amatsu_Bead_!"
AegisName: "Anti-Magic_Suit"
AegisName: "HD_Elunium_Box(30)"
AegisName: "HD_Oridecon_Box(30)"
AegisName: "RWC_Crown_Of_Victory(1st)"
AegisName: "RWC_Crown_Of_Victory(2nd)"
AegisName: "RWC_Crown_Of_Victory(3rd)"
AegisName: "RWC_Crown_Of_Victory(8th)"
AegisName: "C_Baby Dragon Hat"
AegisName: "C_Phoenix Crown"
AegisName: "C_Brown Beanie"
AegisName: "C_Holy Marching_Hat_J"
AegisName: "C_Ph.D_Hat"
AegisName: "C_Loki_&_Nidhoggur_dolls"
AegisName: "C_Well-Chewed_Pencil"
AegisName: "C_Mans_Medal(Gold)"
AegisName: "TE_WoE_Two-Handed_Sword"
AegisName: "Infinity_Two-Handed_Sword"
AegisName: "Crimson_Two-Handed_Sword"
AegisName: "T_VIT1_Earrings_Shadow(R)"
AegisName: "T_INT1_Pendant_Shadow(L)"
AegisName: "T_VIT2_Earrings_Shadow(R)"
AegisName: "T_INT2_Pendant_Shadow(L)"
```

I can safely add the `.` character, but I can't add those others, since they all have another meaning to the script engine.

For those and any future incompatible names, I think we could replace every unsupported character with an underscore `_` in the AegisName.

**Comment by Emistry** [comment]
how about if not alphanumeric then just convert all to underscore `_` ? 

btw, it seem like some items name or more is getting longer than 24 characters now..

**Comment by AnnieRuru** [comment]
I guess sometimes has to resolve to using quotation mark ?
```
prontera,155,185,5	script	kjdhfskf	1_F_MARIA,{
	getitem "Bapho_Jr._Egg", 1;
	getitem "Thanatos_Two-Handed_Staff", 1;
	getitem "True_Howard_Alt-Eisen_Card", 1;
	getitem "Amatsu_Bead_!", 1;
	getitem "Anti-Magic_Suit", 1;
	getitem "HD_Elunium_Box(30)", 1;
	getitem "HD_Oridecon_Box(30)", 1;
	getitem "RWC_Crown_Of_Victory(1st)", 1;
	getitem "RWC_Crown_Of_Victory(2nd)", 1;
	getitem "RWC_Crown_Of_Victory(3rd)", 1;
	getitem "RWC_Crown_Of_Victory(8th)", 1;
	getitem "C_Baby Dragon Hat", 1;
	getitem "C_Phoenix Crown", 1;
	getitem "C_Brown Beanie", 1;
	getitem "C_Holy Marching_Hat_J", 1;
	getitem "C_Loki_&_Nidhoggur_dolls", 1;
	getitem "C_Well-Chewed_Pencil", 1;
	getitem "C_Mans_Medal(Gold)", 1;
	getitem "TE_WoE_Two-Handed_Sword", 1;
	getitem "Infinity_Two-Handed_Sword", 1;
	getitem "Crimson_Two-Handed_Sword", 1;
	getitem "T_VIT1_Earrings_Shadow(R)", 1;
	getitem "T_INT1_Pendant_Shadow(L)", 1;
	getitem "T_VIT2_Earrings_Shadow(R)", 1;
	getitem "T_INT2_Pendant_Shadow(L)", 1;
	end;
}
```
All OK

its fine to use more than 24 characters in constants, variable name ... etc
in fact when Ind improve script engine he seems to lift this limitation

currently the `'` symbol has been used widely as constant, like
`Pecopeco's_Feed`, `Mother's_Cake` ... used a lot already
I hope the `'` symbol isn't converted

`C_Baby Dragon Hat` ... now I wonder what happen if actually type this in Aegis ...

**Comment by dastgir** [comment]
Aegis don't support whitespace in itemname,

**Comment by MishimaHaruna** [comment]
Then we definitely have some wrong AegisNames. They also have a special meaning for ampersand `&`, minus `-`, parentheses `()`, so those might be wrong as well.

@AnnieRuru Yes, using a string would work for that specific case. But it'd work only with commands that take an item name, and wouldn't get any validation (with the new scripting engine), since it's not read as a constant at parse time, but only at runtime. It also wouldn't work if you want to fill an array with item IDs, and then call getitem with them.

About the apostrophe `'`, it's not a problem it can stay as it is, since we've already patched libconfig and the script parser for it.
