### ISSUE TITLE
(default server misconfiguration) Skill range bypass: 14 cells skills usage

### ISSUE THREAD

**Issue by 100percent-zz** [HerculesWS/Hercules#841]
Just a followup to this issue:

http://herc.ws/board/tracker/issue-8302-potnd-bypass-range-skill-delay/

This bug is still existent in the present build of Hercules ( and rathena too! ) but not on any eathena servers.

How to reproduce:

1 - Record packet via WPE / RPE.
2 - Send the recorded packet.
3 - Try to send the packet outside the range of skills.

NOTE: If you followed the temporary fix on the link above...it would only fix the vertical and horizontal range of the skill..but if you try the diagonal way - the bug still persists! I have a screenshot of a guild abusing this, please see screenshot below:

http://i.imgur.com/TPmzNxt.jpg

As you can see, their guild programmer made a program that modify the client binaries to prevent the client from sending the move packet when using skills...that's why it turns out to be behaving like it's only sending packets without moving - and the bug shows up! Notice how he is casting dispell outside the correct range. Please fix this, a cheat that is on its way on becoming famous is abusing it ( xrag ) and its not healthy for the competitive WoE community and the whole RO community in general.

**Comment by kyeme** [comment]
@MishimaHaruna @4144

**Comment by anacondaqq** [comment]
i can confirm this issue since 2012. Still not fixed, and very dangerous.

**Comment by 100percent** [comment]
The range exploit is the most OP and must be fixed immediately because this is a GAME BREAKING bug! Imagine 7 cells Asura Strike and Sonic Blow!?

The sad thing here is that...the range hack doesn't work on eathena! What a time to be alive when old codebase are outperforming newer ones and it's left in the dust forever.

I already explained how to reproduce the bug, I hope some devs can try and see the bug for themselves..to see how alarming this stuff exists since forever...

**Comment by anacondaqq** [comment]
oh, @100percent i've report about bugs since 2011, nobody listen to me, i will be surpriced, if someone will react of this. Usually people do not care about it, and do not understand a lot of child-problems is result of this issue. eAthena have a lot of mechanic-breaking things, and most of them fixed already at rAthena & Hercules, but not all, still a lot of them exist, and they are reported at their bugtrackers or at issues.

**Comment by anacondaqq** [comment]
Btw, many people do not even hear about sit bug, when you can break any mechanic behavior because of fast sitting. A lot of software using that shit to make instant asura strike after body relocation. And this bug still not fixed:)

**Comment by 4144** [comment]
Look like all exploits from message is client changes to avoid client limitation. They not break any server settings. Yes default server settings can be not good. Like skill delays.
Any client protections can be and will be breaked.
Explots must avoide some server settings, only after this it can be fixed on server. For example old eathena cloning items. This is real exploit.

I not sure how aegis working, but from hercules comment in file src/config/core.h:
/// Uncomment to enable circular area checks.
/// By default, most server-sided range checks in Aegis are of square shapes, so a monster
/// with a range of 4 can attack anything within a 9x9 area.
/// Client-sided range checks are, however, are always circular.
/// Enabling this changes all checks to circular checks, which is more realistic,
/// - but is not the official behaviour.
//#define CIRCULAR_AREA

Commented define this mean this feature disabled.

**Comment by dastgir** [comment]
@anacondaqq
We don't replicate everything in aegis, we just have to know if there's a bug, if no one reports, we surely would have no idea about the bug...

**Comment by anacondaqq** [comment]
@dastgir I have no negativity towards the developers. You guys good. You rock. Thank you for your works. But, dear devs., if you will have a some amount of time, please improve basic security things for herc / ra. Thx. Reports available above.

**Comment by Rytech2** [comment]
I wasnt aware of exploits this severe. Kinda makes me want to look into issues like this. Bypassing range limits? Thats a very bad thing.

**Comment by kyeme** [comment]
Actually editing luafiles/skillinfoz can affect range of some skill xD

**Comment by Rytech2** [comment]
Really???? I never knew that. Im looking into server side methods to fix this issue. There needs to be a check where the server expects a certain range or lower to be sent from the client. But there's also this thing of if the caster needs to talk closer or not. A bit tricky.

**Comment by Heler** [comment]
@anacondaqq 

Hello! You wrote: "The current problem of each of protections above -> they are signature based."

You are wrong. Almost all functionality of Gepard Shield is not signature-based. It blocks methods of cheating. Not specific cheat software.

I agree with you, that problem with cheaters can be partially solved on server-side. ;-)

**Comment by ermanherman** [comment]
hi is this problem sloved?

**Comment by kyeme** [comment]
Up

**Comment by Keysito** [comment]
How was the progress of this Exploit?

**Comment by anacondaqq** [comment]
Don't worry @Keysito nobody will fix bugs posted by me above. You will not find any motivated and experienced guy with a lot of time for developing complete product and for supporting this product for next 2-3 years. I'm talking about server-client side protection, where around 99% checks should be done at server-side (yes, it will be heavy CPU application).

#### For people who will try to fix problems above:
You can do that. Because mostly all cheaters with whom i have contacts in past - newbies, and not professional developers, they just know several tips and tricks, and nothing more, and time to time they are using solutions developed by really smart asians (japanese / chinese guys). But even with them nobody can fight, because of luck in motivation.

**Comment by Kenpachi2k13** [comment]
Was fixed in #1457.
