### ISSUE TITLE
Item Script Behavior

### ISSUE THREAD

**Issue by Jedzkie** [HerculesWS/Hercules#884]
I noticed in Aegis, if I use this item (ID#12755 Traditional Firecrack) its not working in Hercules, even though the script are same. (Maybe the behavior in source?)

Example:

In Aegis:
		specialeffect2 EF_POK_JAP;    <---- this part triggers.
		itemskill MO_CALLSPIRITS,3;       <---- this part triggers. (w/ cast)
		itemskill MO_FINGEROFFENSIVE,5;    <---- this part triggers. (changes the cursor to a circle that can be casted on monsters/players)

in Herc:
		specialeffect2 EF_POK_JAP;    <---- this part triggers.
		itemskill MO_CALLSPIRITS,3;  <---- not working.
		itemskill MO_FINGEROFFENSIVE,5;   <---- not working (but changes the cursor to a circle that can be casted on monsters/players)

@MishimaHaruna @kyeme @4144 @AnnieRuru

**Comment by AnnieRuru** [comment]
itemskill script command sux
sometimes has to use `unitskilluseid`
I found this script command inside item_db.conf though

**Comment by MishimaHaruna** [comment]
`itemskill` requires the client's cooperation in order to work. It sends out a packet to the client, and the client will cast the skill (showing the target cursor when needed). It doesn't support chaining multiple instances, there can only be one at a time. Using it twice, will overwrite the first call (we don't have any way to make it pause the script and resume when the skill was cast or canceled, because as far as I'm aware, the client doesn't tell us if/when you cancel a skill without casting it).

As AnnieRuru suggest, using `unitskilluseid` should work, at least for the `MO_CALLSPIRITS` part.
