### ISSUE TITLE
THQS QUEST

### ISSUE THREAD

**Issue by dastgir** [HerculesWS/Hercules#928]
It have item 1999 (Zed's Staff), but our db don't have it , nor I can find any info about it...
@Jedzkie , do you know anything about it?

**Comment by Jedzkie** [comment]
you can find it in item_db2.conf

**Comment by AnnieRuru** [comment]
1. but this item is commented out right ?
means if somebody load this npc, and the server will throw error on that line
because this item isn't registered in `item_db` database, nor it even loaded

2. the deny usage is weird ... very weird
https://github.com/HerculesWS/Hercules/blob/master/npc/custom/quests/thq/THQS_QuestNPC.txt#L47
`set #THQ_DELAY, (gettime(GETTIME_YEAR)*12*31*24+gettime(GETTIME_MONTH)*31*24+gettime(GETTIME_DAYOFMONTH)*24+gettime(GETTIME_HOUR)+rand(2,3));`
this is the 1st time I see somebody doing deny usage like this, not using gettimetick(2)
its set to `*12*31*24` in the month ...
means, if that month only has 30 days, player has to wait 26~27 hours instead of 2~3 hours ?

**Comment by Jedzkie** [comment]
Hahahaha lol. So you are suggesting to enable that item to our item_db.conf?

**Comment by AnnieRuru** [comment]
well, can you verify how the "Treasure Hunter Quest" come from ?
it looks like official conversion, but its inside /custom/ folder

**Comment by dastgir** [comment]
It's not official, else I would have never opened this issue...
I cannot find it in aegis, nor any info of those items

**Comment by dastgir** [comment]
Maybe this is server specific script?

**Comment by AnnieRuru** [comment]
no ... 
https://trac.eathena.ws/browser/branches/stable/npc/quests/thq?rev=1566
>1.0 - Straight conversion of Aegis NPC file
hmm .. feel like it was removed on later date
