### ISSUE TITLE
Create a new Label [codereview:needreview]

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#967]
after Frost and hemagx join our team, suddenly feel like our work flow become more efficient
probably because they play with the Labels
https://github.com/HerculesWS/Hercules/labels

I am actually thinking that, after we pull request, and when its ready
we need someone to review our code, can change from [status:inprogress] into [status:ready]
so I'm thinking that adding a new tag 
[codereview:needreview]
so we assign someone in the team, with this tag on, to ask that particular person to review our code

so what do you think @MishimaHaruna ?

**Comment by hemagx** [comment]
i believe PR under status:ready goes to code review by haruna, and then codereview: status after haruna review;

**Comment by AnnieRuru** [comment]
whats the point of Haru do [codereview:accepted] if he can finally merge it into github ?

**Comment by hemagx** [comment]
it's the point when the PR is fine, but it's not the time to merge ? for example my item type 11 PR, even if it's finished and code review accepted, such huge change can't be merged right away.

**Comment by AnnieRuru** [comment]
After I saw Haru's personal Trello, now I understand how he process our pull request
so yeah, even the stuffs that merge by 4144 he also wants to review again x.x

**Comment by MishimaHaruna** [comment]
The labels aren't finalized yet (and still very open to suggestions)

What we have right now (I'll eventually make a page where everything is explained)

- When a pull request is created, the Waffle API automatically adds the status:inprogress label
- When the pull request is ready to review, status:inprogress should be changed to status:ready (if the pull request was submitted by a staff member, then the submitter is encouraged to do this)
- After review, the reviewer sets one of the codereview: labels, depending on the review outcome.
- If the review is accepted, the reviewer can merge it directly, or wait for me to merge it (for example in case there's some rebasing to be done). I'll merge anything with codereview:accepted when I see it.

This is the workflow I planned for a bug report ticket:

```
1. ticket creation
`-> 2. the issue gets validated
    |-> 2.a status:needinfo if adidtional info from the submitter is needed
    |   `-> Back to 2.
    |-> 2.b status:duplicate (and a link to the original) if there already is a ticket about the same issue
    |   `-> Closed
    |-> 2.c status:unreproducible if the issue can't be reproduced (anymore)
    |   `-> Closed
    |-> 2.d status:wontfix if it's something we can't do anything about (ex. client issue or something by design)
    |   `-> Closed
    |-> 2.e status:invalid if the ticket is invalid or unacceptable for any reason (mistakes, etc)
    |   `-> Closed
    |-> 2.f status:need-aegis-confirmation if further verification on official servers is needed
    |   `-> Back to 2.
    `-> 2.g status:confirmed once the issue is confirmed
        `-> 3. status:inprogress + change of assignee once someone starts working on a fix or an implementation
            `-> 4. issue fixed and closed. status:inpogress is automatically removed.
```

This is the workflow I planned for a pull request

```
1. Pull request creation. status:inprogress is automatically added.
`-> 2. status:ready when the submitter decides there's no more work to do and it should enter code review
    |-> 2.a codereview:rejected if the pull request isn't accepted (there already is a better implementation, or it is otherwise unacceptable)
    |   `-> Closed/rejected
    |-> 2.b codereview:needsedits if the pull request needs some changes, but it is acceptable
    |   `-> Back to 1.
    `-> 2.c codereview:accepted if the pull request is accepted as is
        |-> 3.a Merged and closed using the big green button (status:ready is removed automatically)
        |   `-> Done. Merged.
        |-> 3.b Merged manually by rebasing the commits (status:ready is removed automatically, if closed using the commit message github tricks)
            `-> Done. Merged.
```

The Trello thing enters into play after a week or two, when I have an additional look at every commit, and take note of whether there's something new that came up because of it, and either open a new issue, or fix it.

If anyone has suggestions on how to improve this, please let me know
